### ISSUE TITLE
Appium support

### ISSUE THREAD

**Issue by enricostano** [cheezy/page-object#193]
Hi there,

I'm using `page-object` gem in our acceptance test framework and we're including support for [Appium](https://github.com/appium/appium) to test our iOS and Android apps too.

It would be great to have Appium as a supported platform in this awesome gem! :smiley: 

We could help obviously, any idea/suggestion?

thanks!

**Comment by hardik-d** [comment]
so no single gem yet @bootstraponline ?

**Comment by hardik-d** [comment]
i am looking for something that works with rspec and android/ios/web for appium

**Comment by bootstraponline** [comment]
I'm currently doing angular.js web testing so page-object works fine as is (even with appium). [I don't use appium](https://github.com/appium/ruby_lib/issues/337) for native mobile automation anymore.

**Comment by tk8817** [comment]
Do any of the awesome folks in this thread have an updated outlook on iOS app acceptance testing in 2016. Appium, especially with the 1.5 release, appears to be the front-runner but I have yet to see a solid page-object wrapper for it in Ruby (or any other language for that matter). Before I go and roll my own, it would be good to know if anyone else is trying that could use a dev.

**Comment by bootstraponline** [comment]
For mobile web testing with appium, I just used page-object. For native app / hybrid app, I made my own.

**Comment by tk8817** [comment]
@bootstraponline I deeply appreciate all you have done to maintain the ruby bindings. We had success extending RDee + Page-Object to play with Appium for web testing on iOS devices, but unfortunately that all fell apart (unstable, felt hacky - even basic scripts) when we started working with native apps. 

My team is now investigating alternatives and we are trying hard to hold onto using Ruby, but after seeing EarlyGrey - I am wondering if it would be wise to to jump.

**Comment by bootstraponline** [comment]
I'm in the process of jumping to EarlGrey/Espresso. appium on mobile didn't work out for me.

**Comment by yuri-karpovich** [comment]
Hey @cheezy , 
Please update us with information about Appium support.

Btw, thank you for your page-object gem - it's brilliant!

**Comment by greens82** [comment]
Hello, 
Any news on how to use page-object or gametel with appium ?
If its doable can you share a project.
Thank you !
