### ISSUE TITLE
Dynamic definition of elements

### ISSUE THREAD

**Issue by piyushpathakqa** [cheezy/page-object#203]
Hey ,

What should be done if element definition of an object has to be changed in runtime, especially for the dynamic elements.
For example- If I have a element in my page like-
element(:txtClipId, :xpath => '//h3/a[@href="/video.html?id={$videoid}"]')

and value of {$videoid}" is dynamic and I have to get it from the test method.

**Comment by tobijat** [comment]
Just a remark: Indexed Properties (https://github.com/cheezy/page-object/wiki/Indexed-Properties) solved the problem @zeljkofilipin mentioned for us.

**Comment by entwanderer** [comment]
Is is possible to get an element dynamically inside an iframe?
