### ISSUE TITLE
Locating generic element by name

### ISSUE THREAD

**Issue by dmfranko** [cheezy/page-object#207]
I'm trying to automate an iOS app using appium,page-object and watir-webdriver.  In appium land we need to deal with elements in a generic sense at the moment.

Page

```
class LandingPage
  include PageObject
  element(:login,:element,:name => "Login")
end
```

In my spec file

```
    @landing_page = LandingPage.new(@browser)
    @landing_page.login_element.click
```

I get the exception

```
     Failure/Error: @landing_page.login_element.click
     Watir::Exception::MissingWayOfFindingObjectException:
       invalid attribute: :name
```

If I look at the finders in page-object / lib / page-object / elements / element.rb, it looks like I should be able to use name, but I must be missing something?

```
      def self.watir_finders
        [:class, :id, :index, :name, :xpath]
      end

      def self.watir_mapping
        {}
      end

      def self.selenium_finders
        [:class, :css, :id, :index, :name, :xpath]
      end
```

**Comment by jkotests** [comment]
Watir used to restrict locators to valid attributes. :name was not a valid attribute for many element types, which resulted in the reported exception. However, in the last year or so, Watir lifted this restriction.

This should now work as expected. If the issue persists, please re-open this.
