### ISSUE TITLE
Waiting for options in dynamically loaded SelectList is painfully slow

### ISSUE THREAD

**Issue by garrmark** [cheezy/page-object#208]
Please see the Stackoverflow post for details.  I'm trying to wait on an option in a large SelectList (~3000 elements) and it's taking a few minutes to iterate through.

http://stackoverflow.com/questions/21995363/waiting-on-large-selectlist-arrays-using-page-object-gem

**Comment by AlexisKAndersen** [comment]
I know this is a few years late and at least a dollar short, but given that this is only waiting for content, this seems like a great application for nokogiri. In the past, when I've had to read a huge number of elements, I have used that technique, and it can be orders of magnitude faster.

I'm closing this issue for now, given the time frame that has passed, but if you are still experiencing this issue and need further assistance, feel free to reopen.
