### ISSUE TITLE
acessing text field in a table cell

### ISSUE THREAD

**Issue by charliwtaylor** [cheezy/page-object#214]
I have an application which is mostly tables, so instead of creating cell elements for every cell , i just declare the table. I can then pass in arguments in the tests to locate the required cell. Such as

get_text_from_table('Row', 'Column')

This works fine for getting text from cells, clicking buttons in cells and getting select lists from cells using code like this

the_table_element[row][column].text
the_table_element[row][column].button_element
the_table_element[row][column].select_list_element

however

the_table_element[row][column].text_field_element

will not work

is a different approach needed for text fields or does this functionality not exist for text_field for some reason

**Comment by AlexisKAndersen** [comment]
Given the more recent changes to page-object, I believe this issue is resolved. I tried this test case and it passed for both watir and selenium. If you still experience this problem after upgrading to the newest version, feel free to reopen.
