### ISSUE TITLE
[FEATURE] Suggestion - Page Hooks

### ISSUE THREAD

**Issue by Ricardonacif** [cheezy/page-object#245]
Guys, what do you think of creating an API for some hooks like:

    before_load :set_cookies, :whatever
    after_load :change_current_language, :wait_for_ajax_loading, :whatever

Would that be useful?

**Comment by AlanLGuy** [comment]
I could see some value in having a before_load or after_load hook. I've run into a few situations when there is a method that I want to call after the page is loaded instead of on page initialization.

**Comment by daneandersen** [comment]
@Ricardonacif is there still interest in this? 

Because inizialize_accessors gets called before page load and initialize_page gets called after page load, I don't see a need for a new hook. Do you have an example of something not possible through that?

**Comment by Ricardonacif** [comment]
Yeah, as you pointed @daneandersen, I can't come with any example not covered by that. Will close this.
