### ISSUE TITLE
Deprecated locator text_field works correctly, textarea locator fails for same element

### ISSUE THREAD

**Issue by chrismcmahon** [cheezy/page-object#248]
I was getting warnings from page_object saying "Locating textareas with '#text_field' is deprecated. Please, use '#textarea' method instead."

But when I went to replace #text_field with #textarea my tests no longer could find the element in question. 

I made a demo:

Feature file: 

```
Feature: Textarea bug demo

  Scenario: Deprecated locator works fine
    Given I am on the Flow page
    When I type into the texarea using text_field
    Then typing works

  Scenario: Correct locator does not find element
    Given I am on the Flow page
    When I type into the texarea using textarea
    Then page_object fails to find the textarea
```

Steps file: 

``` ruby
Given(/^I am on the Flow page$/) do
  visit FlowPage
end

When(/^I type into the texarea using text_field$/) do
  on(FlowPage) do |page|
    page.new_topic_title_text_field_element.when_present.click
    page.new_topic_title_text_field_element.when_present.focus
    page.new_topic_title_text_field_element.when_present.send_keys("This is text_field")
  end
end

Then(/^typing works$/) do
  puts "w00t"
end

When(/^I type into the texarea using textarea$/) do
  on(FlowPage) do |page|
    page.new_topic_title_textarea_element.when_present.click
    page.new_topic_title_textarea_element.when_present.focus
    page.new_topic_title_textarea_element.when_present.send_keys("This is textfield")
  end
end

Then(/^page_object fails to find the textarea$/) do
  puts "Test fails before it gets here"
end
```

Page file: 

``` ruby
class FlowPage
  include PageObject

  page_url "http://en.wikipedia.beta.wmflabs.org/wiki/Talk:Flow_QA"

  text_field(:new_topic_title_text_field, name: "topiclist_topic")
  textarea(:new_topic_title_textarea, name: "topiclist_topic")
end
```

**Comment by kmckee** [comment]
I'm running into this `Locating textareas with '#text_field' is deprecated. Please, use '#textarea' method instead` warning as well, using v1.1.1.  I'm using text_field to access `<input type="text" />` elements.  

I'm not able to use textarea to locate these elements, because the tag doesn't match.

Is using text_field actually wrong?  If so, what should I be using to locate `<input type="text"/>`?

**Comment by titusfortner** [comment]
This is a Watir warning. `text_field` was used as a catch-all for input fields that accept text, but Watir has taken a more specific html5 compliant focus, requiring that elements match their specific type (`text_field` matches `<input type="text">` and `textarea` matches `<input type="textarea">`).
I'm actually not a fan of removing the catch-all approach, but we'll decide soon if we are removing support for it, or removing the warning.

**Comment by AlexisKAndersen** [comment]
I'm closing this, since it sounds like this is entirely on the watir side. If you feel there's something page-object should be doing differently, feel free to comment and reopen.
