### ISSUE TITLE
Feature request to pass a value to the index as a number instead of a string for the indexed_property

### ISSUE THREAD

**Issue by madhavankumar** [cheezy/page-object#256]
I had a need so as to pass the index as a number instead of a string. The question can be found here http://stackoverflow.com/questions/26979331/how-to-pass-a-value-to-the-index-during-runtime-for-the-indexed-property.
Can the index be passed as a number instead of a string?

**Comment by daneandersen** [comment]
Is this still a wanted feature, or did the solution in the stackoverflow question meet the need?

**Comment by madhavankumar** [comment]
It is still a wanted feature. The stackoverflow provided alternatives and a monkey patch to the page-object solution. It would be great if this is implemented. Thank you very much!

**Comment by daneandersen** [comment]
I'm including here the proposed solution from jkotests

> You could modify the Page-Object gem to turn the :index into a number before passing it to Watir. > This can be done by adding the monkey-patch:
> 
> ```ruby
> class PageObject::IndexedProperties::RowOfElements
>   def initialize (browser, index, identifier_list)
>     initialize_browser(browser)
> 
>     identifier_list.each do |identifier|
>       type = identifier[0]
>       name = identifier[1]
>       how_and_what = identifier[2].clone # Cannot modify the original...
>       how_and_what.each do |key, value|
>         if key == :index
>           how_and_what[key] = (value % index).to_i
>         else
>           how_and_what[key] = value % index
>         end
>       end
>       self.class.send type, name, how_and_what unless self.class.instance_methods.include? name
>     end
>   end
> end
> ```
> This would allow the page object to be defined as expected:
> 
> ```ruby
> class MyPage
>   include PageObject
> 
>   indexed_property(:my_index_prop, [
>     [:select_list, :my_select, {:name => 'my_select', :index => '%d'}],
>     [:checkbox, :my_check, {:name => 'my_check', :index => '%d'}]
>   ])
> end
> ```
> 
> Which is used the same as the prior solution:
> 
> ```ruby
> page = MyPage.new(browser)
> p page.my_index_prop[1].my_select_element.attribute('id')
> #=> "1"
> p page.my_index_prop[1].my_check_element.attribute('id')
> #=> "b"    
> page.my_index_prop[1].check_my_check
> p page.my_index_prop[1].my_check_checked?
> #=> true 
> ```
> 
> The disadvantage of course is that you have to patch the Page-Object gem. Though you could  request the change be made to the project.

**Comment by daneandersen** [comment]
this enhancement will be in the next release
