### ISSUE TITLE
How to use Page-Factory without cucumber framework

### ISSUE THREAD

**Issue by dprabhua** [cheezy/page-object#258]
Hi Cheesy,

I want to use the page-factory concept but i'm not using the cucumber framework.
When I am looking for solution for dynamic page url using page-object and came across this concept, I tried implementing, 

In admin_case.rb , i gave
require 'page-object'
require 'page-object/page_factory

def addplan
                visit_page AdminPage :using_params => {:page => 'plans'}
end

In admin_pages.rb, i gave 

class AdminPage
include PageObject
 page_url("https://baseurl.com/#admin/<%=params[:page]%>")
end

On running I am getting 
undefined method `AdminPage' for #<AdminCases:0x00000002037f58>

Please confirm where i am wrong in implementing or any alternate solution for using multiple url and dynamic url.

Also, I am looking for setup and teardown solution

**Comment by cheezy** [comment]
In order to use the PageFactory methods they need to be included in the class (or script).  After you call to `require 'page-object/page_factory'` add `include PageObject::PageFactory`
