### ISSUE TITLE
Clarify selection of child elements

### ISSUE THREAD

**Issue by AndreKanig** [cheezy/page-object#260]
I know this has been discussed several times here in the issues, but i still have problems getting the point in selecting arbitrary child-elements from elements generated by page-object.

**Example HTML:**
I have a page and on that page there is a div element containing a dynamically build unordered list.
```
<div id="tree">
  <ul>
    <li path="/Data"
      <ul>
        <li path="/Data/Stuff">
          ...
        </li>
      </ul>
    </li>
    ...
  </ul>
</div>
```
(simplified version, tree can have multiple number of nodes and depth)

**Example Class:**
```
class MyAwesomePage
    include PageObject

    div(:treeview, :id => 'tree')

    def get_leaf(path)
        # how can i get childnodes based on the defined 'treeview' element and xpath?
        treeview_element.element(:xpath => "//li[@path='#{path}']")
        treeview_element.li(:xpath => "//li[@path='#{path}']")
        treeview_element.li_element(:xpath => "//li[@path='#{path}']")
    end   
end
```
All three methods listed in the get_leaf method dont work. Either I get a deprecation warning from the page-object or a ```wrong number of arguments``` error.

What I basically want is, define an element in the class and use this element later as entry point for further locating its child elements. Im pretty sure that this must be possible. Could you provide some examples for achieving this?

Thanks in advance!

**Comment by cheezy** [comment]
fabrice31 is right.  You need to call the *_element method.  This is by design.
