### ISSUE TITLE
Feature request - page sections

### ISSUE THREAD

**Issue by daneandersen** [cheezy/page-object#263]
I want the ability to create classes that represent a portion of a page, possibly repeating. I wrote out the tests and code and submitted a pull request #262 with my implementation of it. 

Let me know if you want me to adjust anything, or feel free to modify anything you like, as long as I can write a class that represents a partial page, I can "declare" elements on it, and the elements within it are rooted to a specific element (i.e. cannot access an element outside of the root).

**Comment by daneandersen** [comment]
I submitted a second pull request with a different(I think better) approach on the same feature.

**Comment by daneandersen** [comment]
>Hi, Dane!
>Can you give some examples of how and when we can use this functionallity?
>Page-object gem has some not obvious aspects. Why we should have page sections (split pages into >small classes) and increase the difficulty?
>@Evmorov

At the heart of it, page sections make it so that you have narrow the focus of a page object to a specific element on the page and its children. This makes identifying important elements easier because we will never accidentally pick up elements outside the scope we are looking in.

The biggest value I see to this is when you are working with a large page with a lot of functionality to it. To reason about this, I'm going to use the example of amazon.com.

There are two main ways sections add value. Breaking down large conceptual areas, and representing collections of related elements.

# Breaking Down Large Conceptual Areas

On any given page of search results on amazon, you have a few different areas of concern:
1. Search results
2. Filters on the results
3. Menus and Navigation
4. Search and sort bars

This is more complex than some websites, but still less complex than some websites I've worked on.

Now we could put all these concerns into one page object but the number of methods grows a lot. We can break it up into modules based on these areas, but at the end of the day, including all these modules in one place means the instantiated object has the same number of methods, and we have just as much risk, if not more, of having collisions between method names. We could make separate page objects for each section, but it sounds hacky with the DSL and can lead to some ugly code. For example if I have these page objects for the areas of the page:


    class SearchBar
      include PageObject

      text_field(:bar)  # if it's the only text field in the section we don't need to identify it
      button(:go) # if we are not using page sections, the search is within the whole page

      def for search_term
        bar = search_term
        go
      end
    end
      
    class Filters
      include PageObject
      link(:prime_eligible, id: 'whatever_id')
    end

Then I can currently use them together using a page object like this:

    class SearchPage
      include PageObject

      # whatever elements needed for reasoning about search results
    end

    on SearchBar do |page|
      page.search_for 'ruby books'
    end
    on Filters do |page|
      page.check_prime_eligible
    end
    on SearchResults do |page|
      # verify results are all prime eligible
    end

Or by treating each area as a section, I can put it together on one page but with encapsulation like the separate pages:

    class SearchPage
      include PageObject

      page_section(:search, SearchBar, id: 'search_bar_section')
      page_section(:filters, Filters, id: 'filters_section')

      # whatever elements needed for reasoning about search results
    end

    on SearchPage do |page|
      page.search.for 'ruby books'
      page.filters.check_prime_eligible
      # verify results are all prime eligible
    end

Yes, the code for setup is longer, but the code of use is shorter and cleaner. If I could choose to have to do more thinking in my implementation of hitting the page, or in my test that is hitting the page to test something, I would choose in the implementation every time. 

# Representing Collections of Related Elements

Having a collection of page sections makes dealing with multiple collections of related elements far easier. To demonstrate, I'm going to talk about amazon again. If we are trying to test the search results, we need some way to go through all the results and reason about them. This is a big pain point right now. If I use indexed properties:

    class SearchPage
      include PageObject

      indexed_property(:results, [
        [:link, :name, id: 'search_result_name_[%s]'],
        [:image, :prime_icon, id: 'search_result_prime_[%s]']
      ])
    end

I can reason about any given result by doing `page.results[0].name` and `page.results[0].prime_icon_element.visible?` but I have no way of testing whether all the results are prime eligible without using some element collection to identify how many there are in the first place and building a loop out of the size.

Probably a cleaner approach is using collections of elements:

    class SearchPage
      include PageObject
  
      links(:name, id: /^search_result_name_[\d+]$/)
      images(:prime_icon, id: /^search_result_prime_[\d+]$/)
    end

Using collections like this, I can find the index of a result with a specific name, and use that index for other collections, but depending on how the prime eligibility images are set up, I might not be able to link it up to results 1 to 1. I can reason about the whole collection of any 1 piece, but if any element happens on some results, but not others, I lose a lot of information.

If I want to use sections:

    class SearchPage
      include PageObject

      page_sections(:results, SearchResult, class: 'search_result')
    end

    class SearchResult
      include PageObject

      link(:name, id: /^search_result_name_[\d+]$/)
      image(:prime_icon, id: /^search_result_prime_[\d+]$/)

      def prime_eligible?
        prime_icon_element.visible?
      end
    end

I can reason about the set of results and ask about each one. Further, I can define specific methods to reason about a section further:
  
    on SearchPage do |page|
      page.results.each do |result|
        expect(result.prime_eligible?).to be true
      end
      # or shorter still expect(page.results).to all(be_prime_eligible)
    end

Because the collections are enumerable, we have the full power of the enumerable methods to help us process and reason about the data. This becomes even more important when we have collections within collections. Because each section scopes at a specific element, we can never accidentally identify the elements from another section. For example, if search results also had inline reviews listed, I could ask for page.results[0].reviews, and know I'm only getting reviews from inside the first result.

**Comment by jkotests** [comment]
I think what you are trying to achieve makes a lot of sense. I have being using a custom page-object framework since I test using Watir-Classic, which is not supported by this gem. I have also been using the concepts of breaking down large areas and having element collections; both of which have made the code much easier to read and use.

However, I do wonder if adding a new "sections" feature is the right approach.

Have you tried using the "widgets" feature to do the same as the proposed "sections"? I think that with some improvements, the widget feature might be able to do the same. For example, on a [recent StackOverflow question](http://stackoverflow.com/a/28368355/1200545), I had used the widget feature to treat a table as a collection of related elements. There are some improvements that we could make to the widget feature to make that answer much closer to what you have written - ex allowing accessors in the widgets.

**Comment by daneandersen** [comment]
@jkotests That's actually exactly what I did. I ran that way for about 6 months. That was part of the reason that enabled collections of widgets, which was just missing some of the plumbing. But I wanted to make the approach more accessible to more people. With widgets you have to give 3 names just to put on 1 widget:
    
    class MyCustomWidget < PageObject::Elements::Div
      extend PageObject::Accessors  # to get the accessor methods
      attr_reader :platform                 # the accessor methods don't work without a platform
    end
    register_widget :my_custom_section, MyCustomSection, :div

    class ThePage
      include PageObject

      my_custom_widget(:must_be_a_different_name, id: 'whatever')
    end

    on ThePage do |page|
      page.must_be_a_different_name_element.whatever_method_i_defined 
      page.my_custom_widget_element # finds the first instance of that tag on the page so you can't use the same name
    end

In practice, I found that newbies had a lot more trouble digesting all this because with so many moving parts to accidentally get wrong, it felt like a magic incantation instead of code. So I tried to at least solve the three names problem by making an accessor method that wrapped a widget. When I went about implementing it with TDD, using a widget to solve the problem was never the next logical step. 

I ended up with an implementation of a class that you inherit that itself inherits from Element. This worked out pretty well too, but what I found after a while is that under the hood it behaved like an element, not like a page. Indexed properties didn't work at all (and gave a cryptic failure message) and default wait times were 5 seconds instead of 30. I'm sure there were more impacts, but at that point I started #264 to address that issue. The end result was you can just use a page object with an element instead of passing in a browser if you want, and the accessor methods to set up such an instance. Honestly, I think this is way more accessible to newbies, because everything is just a class, and you don't have to come up with extra names for things.

**Comment by jkotests** [comment]
Your points are fair from an implementation perspective, but I am struggling to grasp the difference from a use case perspective - ie are "sections" trying to solve a different set of use cases than "widgets".

When would you tell a newbie to use "widgets" vs "sections"?

**Comment by daneandersen** [comment]
I would use a widget when I am trying to model an element on the page. 

In an app I have worked on there is a checkbox that is styled by having a label smack dab in front of it. You click the label to trigger the checkbox, and you look at the checkbox to see if it is checked. I feel like this is a perfect candidate for a widget. It doesn't have extra behaviors, it behaves like a checkbox, but the implementation is a little different. With a little code in a widget, I can make its use in code as simple as using a checkbox.

Honestly it comes down to design at some level. I make the decision based on whether I feel like I'm defining a kind of element, or a part of a page. The more new behaviors and elements I need to define, the more it feels like a section of a page. The more it behaves like an existing element type, the more it feels like a widget.

**Comment by daneandersen** [comment]
This feature will be in the next release

**Comment by snowe2010** [comment]
Any countdown on the next release?

**Comment by cheezy** [comment]
I would expect it to happen fairly soon.

**Comment by snowe2010** [comment]
Great! I can't wait, this will be really useful to us as our application has quite a few fields.
