### ISSUE TITLE
Unable to get option text from a hidden select

### ISSUE THREAD

**Issue by danielfariati** [cheezy/page-object#268]
Hi.

When I try to get the text from an hidden option, it's returning an empty string.

For example:
```html
<select style="display:none;">
  <option value="1">Text</option>
</select>
```
```ruby
@page.select_element[0].text.should eq "Text"
```
```bash
Failure/Error: @page.select_element[0].text.should eq "Text"
       expected: "Text"
            got: ""
```

As a workaround, I'm calling ".label" instead of ".text". If I do this, the test passes, but it keeps showing an annoying Deprecation Warning:
```html
<select style="display:none;">
  <option value="1">Text</option>
</select>
```
```ruby
@page.select_element[0].label.should eq "Text"
```
```bash
*** DEPRECATION WARNING
*** You are calling a method named label at PATH:LINE:in `block (3 levels) in <top (required)>'.
*** This method does not exist in page-object so it is being passed to the driver.
*** This feature will be removed in the near future.
*** Please change your code to call the correct page-object method.
*** If you are using functionality that does not exist in page-object please request it be added.
Finished in 4.51 seconds
1 example, 0 failures
```

**Comment by AlanLGuy** [comment]
This isn't an issue with page-object. This is a behavior of the driver. An element which is hidden will return an empty string when asked for it's text. The same behavior would occur whether you are accessing a Div or a Span or any other element for that matter. 

if you called:
`@page.select_element[0].element.text`  which accesses the drivers element directly, you would get the same behavior

If you want to get rid of the deprecation warning, access the driver before calling .text. 
    `@page.select_element[0].element.label.should eq "Text"`

**Comment by danielfariati** [comment]
Got it!
Thanks.
