### ISSUE TITLE
Reference to indexed property only returns values of the first element

### ISSUE THREAD

**Issue by haploke** [cheezy/page-object#269]
We're using page-object for our internal QA and we saw that when upgrading from version 1.0 to 1.0.3 some routines stopped working the way they used to.
After some debugging, it seems that references to indexed properties always return the values of the first element rather than the values of the requested index.

Here is some code to run a test which results in the issue. 2 files: test.html and test.rb

test.html
-----------
<code>&lt;html&gt;<br>
&lt;body&gt;<br>
&lt;table class="table_class"&gt;<br>
    &lt;tr&gt;<br>
        &lt;td&gt;&lt;span id="title"&gt;Item 1&lt;/span&gt;&lt;/td&gt;<br>
        &lt;td&gt;&lt;span  id="description">First item</span>&lt;/td><br>
        &lt;td&gt;&lt;input type="button" id="delete" value="Delete" onclick="..."/&gt;&lt;/td&gt;<br>
    &lt;/tr&gt;<br>
    &lt;tr&gt;<br>
        &lt;td&gt;&lt;span id="title"&gt;Item 2&lt;/span&gt;&lt;/td&gt;<br>
        &lt;td&gt;&lt;span  id="description"&gt;Second Item&lt;/span&gt;&lt;/td&gt;<br>
        &lt;td&gt;&lt;input type="button" id="delete" value="Delete" onclick="..."/&gt;&lt;/td&gt;<br>
    &lt;/tr&gt;<br>
    &lt;tr&gt;<br>
        &lt;td&gt;&lt;span id="title"&gt;Item 3&lt;/span&gt;&lt;/td&gt;<br>
        &lt;td&gt;&lt;span  id="description"&gt;Third item&lt;/span&gt;&lt;/td&gt;<br>
        &lt;td&gt;&lt;input type="button" id="delete" value="Delete" onclick="..."/&gt;&lt;/td&gt;<br>
    &lt;/tr&gt;<br>
&lt;/table&gt;<br>
&lt;/body&gt;<br>
&lt;/html&gt;<br>
</code>

test.rb
---------

require 'selenium-webdriver'
require 'page-object'
class ShoppingCartPage
  include PageObject

  indexed_property(:cart_contents, [
    [:span, :item_title, {:xpath  => ".//tr[%s]//td/span[@id='title']"}],
    [:span, :item_description, {:xpath  => ".//tr[%s]//td/span[@id='description']"}],
    [:button, :item_delete, {:xpath => ".//tr[%s]//td//input[@id='delete']"}]
  ])
end
@browser=Selenium::WebDriver.for :firefox
@browser.navigate.to "http://localhost/test.html"
@page = ShoppingCartPage.new(@browser)

puts @page.cart_contents[1].item_title
puts @page.cart_contents[2].item_title
puts @page.cart_contents[3].item_title
puts @page.cart_contents[1].item_title
puts @page.cart_contents[2].item_title
puts @page.cart_contents[3].item_title

my_variable=@page.cart_contents
puts "Now using a reference  ..."
puts my_variable[1].item_title
puts my_variable[2].item_title
puts my_variable[3].item_title
puts my_variable[1].item_title
puts my_variable[2].item_title
puts my_variable[3].item_title

@browser.close 

OUTPUT
-----------

With page-object v1.0:
$ bundle exec irb
1.9.3-p551 :001 > load  '~/test.rb'
Item 1
Item 2
Item 3
Item 1
Item 2
Item 3
Now using a reference  ...
Item 1
Item 2
Item 3
Item 1
Item 2
Item 3
 => true 

With page-object v1.03:
 $ bundle exec irb
1.9.3-p551 :001 > load  '~/test.rb'
Item 1
Item 2
Item 3
Item 1
Item 2
Item 3
Now using a reference  ...
Item 1
Item 1
Item 1
Item 1
Item 1
Item 1
 => true

**Comment by daneandersen** [comment]
This seems related to issue #230. Page Object 1.0.2 attempted to add protection against re-declaring methods that already exist, but it messed with indexed properties. 1.0.3 addressed this, but it looks like there's still one scenario that is broken. I will look into this and see if there's another fix that can be applied.

**Comment by daneandersen** [comment]
the fix for this will be in the next release
