### ISSUE TITLE
Deprecated warning when using set method on text_field

### ISSUE THREAD

**Issue by sharmarahul** [cheezy/page-object#270]
When using when_visible or when_present on text_field, e.g.

username_element.when_visible.set 'user'

issues the following warning

This method does not exist in page-object so it is being passed to the driver.
*** This feature will be removed in the near future.
*** Please change your code to call the correct page-object method.
*** If you are using functionality that does not exist in page-object please request it be added.

Since the when_visible method returns the Watir element itself, should it throw the error when using set method?

**Comment by jkotests** [comment]
While Watir supports inputting text fields with `set` and `value=`, the Page-Object gem currently only supports `value=`. 

In other words, with the current API, the text field should be set using:

````````ruby
username_element.when_visible.value = 'user'
````````

**Comment by sharmarahul** [comment]
Thanks @jkotests.
