### ISSUE TITLE
1.0.4 release?

### ISSUE THREAD

**Issue by bootstraponline** [cheezy/page-object#272]
Is there anything that needs to be done before the 1.0.4 release?

**Comment by daneandersen** [comment]
There is an outstanding issue with indexed properties that I'm still hoping to address.

**Comment by bootstraponline** [comment]
Is there an issue number for that problem?

**Comment by daneandersen** [comment]
#269

**Comment by daneandersen** [comment]
The 1.1.0 version has been released

**Comment by bootstraponline** [comment]
Thanks!
