### ISSUE TITLE
Add wiki page about methods for html elements?

### ISSUE THREAD

**Issue by bootstraponline** [cheezy/page-object#281]
Watir has a nice wiki page that lists [supported html elements and the proper method to use](https://github.com/watir/watir/wiki/HTML-Elements-Supported-by-Watir). I generated [a similar one for page-object](https://github.com/bootstraponline/page-object/wiki/Methods-for-HTML-Elements), what do you think about adding this to the wiki? If approved, I'll copy it over. I didn't want to mess with the wiki without checking first.

The [elements](https://github.com/cheezy/page-object/wiki/Elements) page is nice however it doesn't answer the question of what method should I use for this html element. It's also missing some such as canvas. I realize that most of these are obvious however page-object allows any html element to be used on any page object method so I think having this documented is useful.

**Comment by daneandersen** [comment]
That looks very useful. Only change I would make is that some of the HTML Tags listed are actually types of input elements. It would be good to call this out somehow. If you can clear that up, definitely add it. Thanks for the addition.

**Comment by bootstraponline** [comment]
Thanks for the feedback. I think I [cleared all the input elements up](https://github.com/cheezy/page-object/wiki/Methods-for-HTML-Tags). If there are any other issues let me know and I'll fix. I've added it to the wiki.
