### ISSUE TITLE
Expand definition of button to include anchor tag

### ISSUE THREAD

**Issue by bootstraponline** [cheezy/page-object#283]
```ruby
# https://github.com/cheezy/page-object/blob/7a3fe249b9d62b7bf921e959b8bd92e5199a86dd/lib/page-object/platforms/selenium_webdriver/button.rb
def text
  %w(button a).include?(element.tag_name) ? element.text : element.attribute('value')
end
```

The current button text method will check the value attribute of an anchor tag which doesn't make sense, it should use the text value instead. Would you accept a patch for this change?

**Comment by daneandersen** [comment]
Wouldn't you just use a link element for an anchor tag instead of a button?

**Comment by bootstraponline** [comment]
I have both input tags and anchor tags acting as "buttons." Is an anchor tag always a link even if it's a button?

```
button1.text # <a>
button2.value # <input>
```

The current design is like this:

button 'some name', css: 'this can return any tag'

If we're returning an anchor tag in response to button, it never makes sense to get the value attribute instead of text. I'm a bit confused on why we'd want to keep the current behavior.

**Comment by daneandersen** [comment]
as far as I can tell, you can't create a page object button element with an anchor tag. When trying to identify it, it responds:

`Watir::Exception::UnknownObjectException: unable to locate element, using {:class=>"spell", :tag_name=>"button"}`

Are you able to create a page object button using an anchor tag?

**Comment by bootstraponline** [comment]
> Are you able to create a page object button using an anchor tag?

Yes, that is how I do all my anchor tags (which I'm starting to realize is probably not the intended usage?)

Here's some code:

```ruby

button 'mr_button',   css: 'a.more.css'

```

Now when I use this in Pry

```ruby
> my_page.mr_button_element.tag_name
=> "a"
```

**Comment by daneandersen** [comment]
I would say in that case, the intended usage is `link :mr_button, css:
'a.more.css'`, in fact in watir-webdriver, it disallows it completely. I
imaging that's not the case in selenium. I will investigate why that is the
case, but I think it comes down to using button on anchor tags is
unsupported.

**Comment by bootstraponline** [comment]
It'd be nice to have the error message raised in selenium as well for consistency. I think with the [method / tag docs](https://github.com/cheezy/page-object/wiki/Methods-for-HTML-Tags) I should be able to figure out the proper usage. I will switch the anchors to use the link class.

**Comment by bootstraponline** [comment]
I tried switching to watir-webdriver (`Watir::Browser.new :firefox`) and the same page object continued to work fine (anchor tag found with css via button method). I'd expect an error in this situation?

**Comment by daneandersen** [comment]
Can you share your code for the element?

**Comment by bootstraponline** [comment]
I posted #285 to track the issue. The app I'm testing is big and complicated. I'll try and create a minimal example which can be shared. I think the pry session explains what's going on, the button watir class isn't used instead it's the more general super class.
