### ISSUE TITLE
[Feature request] image_element.loaded?

### ISSUE THREAD

**Issue by eskignax** [cheezy/page-object#290]
Hello Cheezy Team !

I didn't find any equivalent for the image_element.loaded? method on page-object. Since the deprecation warning ask for it, I create this request.

Thank you.

**\* DEPRECATION WARNING
**\* You are calling a method named loaded?
**\* This method does not exist in page-object so it is being passed to the driver.
**\* This feature will be removed in the near future.
**\* Please change your code to call the correct page-object method.
**\* If you are using functionality that does not exist in page-object please request it be added.

**Comment by jkotests** [comment]
This was fixed/merged in v1.2.1. Since then, we've also removed the deprecation warning.
