### ISSUE TITLE
Better exception handling for nilClasses because element was not found.

### ISSUE THREAD

**Issue by magicalbanana** [cheezy/page-object#301]
Right now it would be great if we could have a way to handle nilClasses better because when setting an element and it does not get set it'll just error as nilClass.

It would be nice if it was more specific.

**Comment by bootstraponline** [comment]
Would you provide an example? I'm not sure what you mean by setting an element.

**Comment by magicalbanana** [comment]
Sorry, this was a unintended. I thought that if an element was not found it would not raise an exception (which it does).

**Comment by magicalbanana** [comment]
Actually, it would be great that if when using select list or any option related element it would specify what element was not able to find the said option.

Right now the exception raised is pretty standard.

It just says option foo was not found select list.

**Comment by jkotests** [comment]
This has been migrated to the Watir project - https://github.com/watir/watir/issues/823
