### ISSUE TITLE
Add default tag name to element

### ISSUE THREAD

**Issue by bootstraponline** [cheezy/page-object#302]
Instead of:

`element 'button', :element, css: 'some css'`

It'd be nice to have a default tag:

`element 'button', css: 'some css'`

I'm happy to submit a [pull request for this feature](https://github.com/bootstraponline/page_object/commit/9813f72eae0a85bd51a35a3f49a10d7732caaa86).

**Comment by williamjablonski** [comment]
I'm needing this correction.

**Comment by bootstraponline** [comment]
I've released this in my fork of [page_object](https://github.com/bootstraponline/page_object) which you're welcome to use. It'd be nice if the official page object was maintained.
