### ISSUE TITLE
Identify an object having data-action in page object model ?

### ISSUE THREAD

**Issue by badrinathvm** [cheezy/page-object#309]
How can i identify the object having html like below 

      " <div data-action="update"> Click </div> "

Can we use some thing like below 

       " div upd_task,  :data-action => 'update' "  

is data-action supported in page object model ?

**Comment by d-konovalov** [comment]
It's something like custom attributes, I can suggest you to use css or xpath to get this element (I prefer css):
css:

```ruby
div :upd_task, css: "[data-action='update']"
```
xpath:

```ruby
div :upd_task, xpath: "*[@data-action='update']"
```

both should work
Best regards

**Comment by jkotests** [comment]
The data-* and aria-* attributes are supported if you are using Watir-Webdriver as the platform.

It would be:

    div :upd_task, :data_action => 'update'

Note that the dashes, '-', in the attribute name need to be replaced with underscores, '_'

**Comment by badrinathvm** [comment]
thanks for the info guys , solution provided by u folks works like charm.
