### ISSUE TITLE
select() returns error when no value/text selected

### ISSUE THREAD

**Issue by chrismcmahon** [cheezy/page-object#310]
Mostly an enhancement, but I'm currently having to work around this: 

Assume you have a select multiple element but with no value selected: 

`<select multiple id="my_id">`
`<option value="volvo">Volvo</option>`
`<option value="saab">Saab</option>`
`<option value="mercedes">Mercedes</option>`
`<option value="audi">Audi</option>`
`</select>`

and 

select(:nothing_selected_box, id: 'my_id')

then

on(MyPage).nothing_selected_box

yields the error "undefined method 'text' for nil:NilClass"

I suggest that upon encountering a select box with nothing selected, the method return an empty string "" rather than error.

**Comment by AlexisKAndersen** [comment]
The fix for this bug is in a branch to get merged and will be in the 2.2.0 release.

https://github.com/cheezy/page-object/pull/432
