### ISSUE TITLE
Identification of dynamic object ?

### ISSUE THREAD

**Issue by badrinathvm** [cheezy/page-object#312]
Below is tag 

 < a href="#dynamicData">details</a>

currently i am identifying the object like below 

 link    :details_link,             :xpath => "//a[contains(@href,'#dynamicData')]"

 is there any other way to identify dynamic object apart from using xpaths ?

**Comment by cheezy** [comment]
You can use :href => “<the value>"

**Comment by badrinathvm** [comment]
Value will be dynamic link gets changed every time.

**Comment by jkotests** [comment]
If you are using Watir as the platform, it supports matching against regular expressions.

The accessor:

    link :details_link, :xpath => "//a[contains(@href,'#dynamicData')]

Would be equivalent to:

    link :details_link, :href => /#dynamicData/

**Comment by daneandersen** [comment]
You can also identify a link by its text if that's any more stable than the href. 

@badrinathvm, are you still experiencing this issue?

**Comment by badrinathvm** [comment]
The solutions provided helped a lot .. Thanks a ton guys.
