### ISSUE TITLE
Request to implement the element.present? method in page-object

### ISSUE THREAD

**Issue by alecdwm** [cheezy/page-object#313]
First, a reference:
From https://jkotests.wordpress.com/2012/11/02/checking-for-an-element-exists-visible-present/
> Back when I started Watir, there was only one method to check for an element on the page – Element#exists?. Now, several versions later, there are three – Element#exists?, Element#visible? and Element#present?.  
> The three methods are not aliases of each other. They are different.  
> How are they different?  
> exists? – Returns whether this element actually exists.  
> present? – Returns true if the element exists and is visible on the page  
> visible? – If any parent element isn’t visible then we cannot write to the element. The only reliable way to determine this is to iterate up the DOM element tree checking every element to make sure it’s visible.

Element | .exists? | .present? | .visible?
-----------|-----------|--------------|----------
Displayed|true|true|true
Not Displayed|true|false|false
Non-Existent|false|false|exception

So, I would like to use the .present? method in my code.  
The issue being that it hasn't been implemented in page-object, so the below gets printed out:
> *** DEPRECATION WARNING  
> *** You are calling a method named present? at [snipped]  
> *** This method does not exist in page-object so it is being passed to the driver.  
> *** This feature will be removed in the near future.  
> *** Please change your code to call the correct page-object method.  
> *** If you are using functionality that does not exist in page-object please request it be added.  

Cheers!

**Comment by jkotests** [comment]
It actually is implemented. The page object uses a different terminology than Watir:

As seen from the [code for WatirWebDriver::Element](https://github.com/cheezy/page-object/blob/f6406edd2dd46a7e13c48677344c00f9fe4ba220/lib/page-object/platforms/watir_webdriver/element.rb#L11-L23):

        #
        # return true if an element is visible
        #
        def visible?
          element.present?
        end

        #
        # return true if an element exists
        #
        def exists?
          element.exists?
        end

The page object maps:
* `visible?` to Watir's `present?` method
* `exists?` to Watir's `exists?` method
* nothing to Watir's `visible?` method

Therefore you should be calling the `visible?` method instead.

**Comment by alecdwm** [comment]
Ah I see!
Thanks for the clarification! :D
