### ISSUE TITLE
Select_list current state is not returned correctly. 

### ISSUE THREAD

**Issue by vveliev** [cheezy/page-object#315]
select_list does not behaving as expected. If select have default value.
Ex1.

```
 select_list(:date, class: 'date_class')
>date
""
>date_element.selected_options
["Custom"]
```

**Comment by daneandersen** [comment]
@vveliev what driver and browser are you using?

**Comment by vveliev** [comment]
I believe it was with selenium-webdriver 2.45 ,  firefox 39
