### ISSUE TITLE
when I'm using image (or img) as element type and src as locator the library is returning "undefined local variable or method"

### ISSUE THREAD

**Issue by williamjablonski** [cheezy/page-object#318]
Locator :  

img :productImg, :src => 'http://ab.wsimgs.com/wsimgs/ab/images/dp/wcm/201533/0266/img51j.jpg'

Implementation:

def clickOnProduct
    sleep 1
    productImg
end

Returned:

undefined local variable or method `productImg' for #<IndexPage:0x00000001cc49c0> (NameError)
      ./features/pages/indexPage.rb:31:in `clickOnProduct'
      ./features/step_definitions/add_product.rb:17:in `/^click on product "([^"]*)"\.$/'
      features/Add_product.feature:10:in `And click on product "product".'

**Comment by jkotests** [comment]
As per the [docs for the `img` accessor](http://www.rubydoc.info/github/cheezy/page-object/master/PageObject/Accessors#image-instance_method):

> adds two methods - one to retrieve the image element, and another to check the image's existence.
>
> Examples:
>
> `image(:logo, :id => 'logo')`
> `# will generate 'logo_element' and 'logo?' methods`

In other words, your page would have a `productImg_element` and `productImg?` method. There would not be a `productImg` method.

**Comment by daneandersen** [comment]
As @jkotests mentioned, that is correct. There is currently no behavior defined for the 'name' method, just name_element and name?
