### ISSUE TITLE
Setup gemnasium to track dependencies

### ISSUE THREAD

**Issue by bootstraponline** [cheezy/page-object#326]
gemnasium is an easy way to track [gem dependencies](https://gemnasium.com/bootstraponline/page_object). They also provide a cool badge that can be inserted in the readme

[![Dependency Status](https://gemnasium.com/bootstraponline/page_object.svg?nocache)](https://gemnasium.com/bootstraponline/page_object)

**Comment by cheezy** [comment]
Thanks for the suggestion.  I'll look into it.
