### ISSUE TITLE
Deep inheritance cause issues with widget loading

### ISSUE THREAD

**Issue by brbrr** [cheezy/page-object#328]
I have such pages structure:
SomePage < AdminPage < BasePage
where only BasePage have `include PageObject` 
in SomePage I use custom widget which is defined as: 

```
class BootstrapSelect < PageObject::Elements::SelectList
    code here
end

PageObject.register_widget :bootstrap_select, BootstrapSelect, :select
```

order of files loaded:

```
require_relative 'all gems required here'
require_relative 'pages/base_page'
require_relative 'pages/admin_page'
require_relative 'widgets/bootstrap_select'
Dir["#{File.dirname(__FILE__)}/pages/admin/*_page.rb"].each {|r| load r }
```

when I trying to run some test I got: 
:in `<class:SomePage>': undefined method`bootstrap_select' for SomePage:Class (NoMethodError)

When I add `include PageObject` in to `AdminPage` - it works
When I require widgets BEFORE `BasePage` - it works

**Comment by cheezy** [comment]
Is there a page-object issue here that can be clearly described?

**Comment by brbrr** [comment]
Thats kinda old issue, and it is not relevant anymore. Looks like I did not get in to require ordering. Requiring widgets before the `include` will fix this issue.
