### ISSUE TITLE
wait_for_ajax is not working with :angularjs for me

### ISSUE THREAD

**Issue by pittgoose** [cheezy/page-object#332]
we have a method defined called `wait_for_script` which passes the specified JS library to PageObject in order to utilize `wait_for_ajax`. Here is the code we use:

``` ruby
module AjaxHelper
  include PageObject
  include TimeoutHelper

  def wait_for_script(script,timeout = 30, message = nil)
    timeout = timeout_by_env(timeout)
    PageObject::JavascriptFrameworkFacade.framework=script
    self.wait_for_ajax(timeout, message)
  end
end
```

and calling this method like this

``` ruby
wait_for_script(:jquery, 10, 'this is the message')
```

We use :jquery all the time and it works great. However we just upgraded to `PageObject v -1.1.0` and I am trying to use this method with :angularjs and I'm getting the following error:

``` ruby
Selenium::WebDriver::Error::UnknownError: unknown error: Cannot read property 'get' of undefined
  (Session info: chrome=45.0.2454.85)
  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64)
./lib/helpers/ajax_helper.rb:8:in `wait_for_script'
```

Any ideas if this is an issue with PageObject or an issue with my implementation?

**Comment by pittgoose** [comment]
Ok, sat with a developer on this and here's why I'm having a problem:
The script run in `page-object-1.1.0\lib\page-object\javascript\angularjs.rb` is:
```
 'return angular.element(document.body).injector().get(\'$http\').pendingRequests.length;'
```
The page I'm trying to implement this on isn't a true AngularJS app, it's a page which contains an AngularJS app inside of it in a div element. So when this script looks for `angular.element(document.body)` it doesn't find anything and returns the error above.

If it's cool with you @cheezy I might play around with this and see if I can make document.body into a variable.

**Comment by cheezy** [comment]
I'm open to any pr that makes this more robust.  Have you had time to play around with it?

**Comment by jkotests** [comment]
Given the age of this, I'm going to close it. Please re-open if you wish to continue investigating solutions.
