### ISSUE TITLE
Page section "Element not found in the cache - perhaps the page has changed since it was looked up"

### ISSUE THREAD

**Issue by vveliev** [cheezy/page-object#337]
Hey , I'm running to the problem such that when i start to convert my existing code (module based) to the sections(Class based) to reduce risk of name collision. Suddenly i start to get error:

```
Element not found in the cache - perhaps the page has changed since it was looked up
```

Altho element is actually on the page , but I'm assuming due to the ajax call of result table refresh , I'am getting this error .

and unless I open reopen page class it does not see element's on the page.

Thanks !

**Comment by vveliev** [comment]
In particular , it 's failing to find root_element

**Comment by vveliev** [comment]
So after spending some time , it looks to me that flow exist in the way how referencing of nested pages work, where when section is created. 

Static element identifier is used to create it. if there are any change on the page, then selenium Id will be different and it brakes. 

As a solution it looks to me that instead of selenium reference object , it should accept identifier and than do all the processing and finding element evry tyme sounds wasteful , then it should at least try to catch element not found ones, refresh reference and try again.

**Comment by daneandersen** [comment]
@vveliev I have seen this problem too. I've been playing around with a couple ideas on how to fix it.

It's just as you observed, the root element itself becomes stale, and then any call to selenium within that will fail. I am thinking about a syntax where you can identify how the element can be relocated.

for instance:
```ruby
class SomeRowSection
  include PageObject

  div :id, class: 'id'

  relocatable by: :id
end
```

So that when the element is located in the first place, it will store the id, and use that to identify it later.

Another option would be to put this syntax on use of the class instead of in the class definition:

```ruby
class MyPage
  include PageObject

  page_sections(:rows, class: 'row').relocatable(by: :id) #Ruby >=2 approach

  page_sections(:rows, class: 'row')
  relocatable(:rows, by: :id)                     #Ruby 1.9 approach
end
```

I still have to work out some of the syntax, but this is what I'm hoping to implement.

**Comment by vveliev** [comment]
I was thinking of replacing:

```rb
@root_element -> @root_identyfier 
```
and move logic of 'find_selenium_page' to the instance.
```rb
        def find_selenium_page(identifier, page_class)
          type, tag = Elements::Element, 'element'
          regexp = delete_regexp(identifier)
          how, what, frame_identifiers = parse_identifiers(identifier, type, tag)
          switch_to_frame(frame_identifiers)
          begin
            unless regexp
              element = @browser.find_element(how, what)
            else
              elements = @browser.find_elements(how, what)
              element = elements.find {|ele| matches_selector?(ele, regexp[0], regexp[1])}
            end
          rescue Selenium::WebDriver::Error::NoSuchElementError
            @browser.switch_to.default_content unless frame_identifiers.nil?
            return build_null_object(identifier, type, tag, nil)
          end
          @browser.switch_to.default_content unless frame_identifiers.nil?
          page_class.new(element)
        end
```


I don't have much experience and learning ruby at the time. but i was thinking of: 
solution 1:
simply use create method that will always find section identifier(logically it's slower but does it really matters ?! ) this will be similar to the nested elements.

solution 2:
save reference to the selenium identifier within the instance have some sort of wrapper that if we get exception then reinitialize reference (only try ones if that fail then throw exception back)

**Comment by daneandersen** [comment]
The biggest problem I see with this approach is in the case of a collection of sections. If I have three rows: (I'm just using a table as a simple enumerable example)

Fruit | Color
-------|-------
Apple| Red
Kiwi | Green
Orange | Orange

If I'm looking at fruits[1] #=> #\<FruitSection\> #kiwi fruit
And I remove the apple row, and (for whatever reason) the app redraws the whole table
If I assume the section at index 1 is what I'm looking for, I'll get orange instead. 

If we can identify the singular defining quality of the row, we can use that to identify it. In this case it's the fruit name.

If I had been examining Apple and changed it to Pineapple, I wouldn't necessarily want to (and likely wouldn't be able to) identify it again. But all that is why I'm hoping to provide a syntax for cleanly stating how you want to identify the lost element.

**Comment by titusfortner** [comment]
Watir automatically relooks up stale elements, so I'm assuming this is only an issue when using this gem exclusively with Selenium?

**Comment by vveliev** [comment]
@titusfortner , I have not checked , and it will take me some time to set up watir to work

**Comment by vveliev** [comment]
@daneandersen  from my knowledge you should not be able to identify section using text or element as a reference, at the level of page element 'section'  
```rb
 page_section(:name, Class, id:/class:/name: 'user_bar')
``` 
As in your exible in order to set single row of the table as a section , you can only do it for the first one , without using something more unique like , name/id/class 

if you look at : "find_selenium_page(identifier, page_class)" , ```identifier = {class: 'css_class'}```
and if you store in at the instance level than you can always find it if it's present. 
 ***NOTE: section_name? - method will be useful as well to check if section present on the page or not.

**Comment by vveliev** [comment]
@titusfortner , Yes this problem selenium specific:
```rb
@root_element
#<Watir::HTMLElement:0x..f7134bf50af6b75e located=false selector={:class=>"navigationToolbar"}>
```
