### ISSUE TITLE
 Undefined method `pending_requests' , when using wait_for_ajax

### ISSUE THREAD

**Issue by vveliev** [cheezy/page-object#339]
Hey, I run into the problem, when i'am using wait_for_ajax, some time i get this error ..... 

It's used right after I do some action on the page . In particular when I performer search and waiting for result page to refresh.

**Comment by vveliev** [comment]
selenium-webdriver (2.47.1)
page-object (1.1.0)
selenium-server-standalone-2.47.1

**Comment by cheezy** [comment]
Which JavaScript framework is being used in your application?

**Comment by vveliev** [comment]
mootools

**Comment by vveliev** [comment]
I guess there should be a wrapper for mootools ... before it can work .....
