### ISSUE TITLE
Ability to change page class from page 

### ISSUE THREAD

**Issue by vveliev** [cheezy/page-object#340]
I'm not aware of any options right now, to change page class, right after .click from page itself. 

I think it will be very useful to have ability changing page class, from page_object.

Ex. 
```rb 
class SimplePage
  include PageObject
  button(:login_bt, id: 'button_id')
  .
  .
  .
  def login(data={})
    .
    .
    .
    self.login_bt
    page_class(SamplePage2)
  end
end
``` 

Thanks

**Comment by titusfortner** [comment]
I have no input on this implementation for this gem, but for the record, while it was considered best practice for a page object pattern several years ago, having one page object return another page object after an action is no longer recommended. I've written such frameworks before and it ends up resulting in a lot more overhead than it helps. 
Discouraged:
```Ruby
visit(LoginPage).login.add_address.make_purchase
```
At this point the community overall agrees that this more easily maintained and more clear:
```Ruby
visit(LoginPage).login
on(AccountPage).add_address
visit(OrderPage).make_purchase
```

**Comment by vveliev** [comment]
hmmm ... when I'm looking  from cucumber standpoint, i like first approach first ... where I whould try to avoid grouping of functions .

```cucumber
  Scenario: start from main page
    Given I am on the Main page
    Then I click on 'login' link
    Then change page class to LoginPage
```
so the step of changing page class seemed to be an overhead.
page_navigation gem, does not looks to be very helpful as it is more specific for testing certain navigation routes. (simulates behavior of the shown in first example)


I guess potential solution to my problem can be that methods who does rederect to the different page return class of interest ....
```rb
class SimplePage
  include PageObject
  button(:login_bt, id: 'button_id')
  .
  .
  .
  def login(data={})
    .
    .
    .
    self.login_bt
    Sample::Page2
  end
end
```
where steps will be of a format:
```rb
When /some step definition (.*)/ do |action|
  on_page(@current_page.send(action))
end 

```

But this requires some additional validations as I may return some other information that will be needed and may be similar to the PageClass

**Comment by titusfortner** [comment]
Gah, Cucumber. Cucumber is actually what lends itself particularly well to *not returning a new page object.
Here's how to replicate your scenario
```
  Scenario: Navigate to Login Page
    Given I start on the Main page
    When I click the login link
    Then I find myself on the Login Page
```
You only need to define an instance variable if there are multiple pages on which you can click the login link. You definitely don't need to know the output of the When Step call, because the desired output is directly specified in the Then statement. The more instance variables in your steps the harder it is to easily understand what they do.

**Comment by vveliev** [comment]
Let's not go into the cucumber....

Anyways I thought it would be useful to have ability to change page class from itself. 

I will return hash with a key: ```:change_page_class ``` and parser that will detect it and change page class when needed.
