### ISSUE TITLE
Redirecting to authentication page

### ISSUE THREAD

**Issue by ducthanh** [cheezy/page-object#341]
Hello, 
I'm getting the Navigation problem in my internal project, when I click into a button then page is navigated to another page which require the authentication info. 
Is there any way to pass the authentication info when user interacts with elements?

**Comment by tk8817** [comment]
@ducthanh you can pass the username & password as part of the URL if you are doing a visit(Page) call. This works great in all modern browsers. 

https://username:password@url.com

I would advise that you pass any special characters in HTML code form

**Comment by vveliev** [comment]
as part of the navigation process you can, have function on the page that does authenticate, if you need to populate username password ....

**Comment by jkotests** [comment]
I'm going to close this. It's a unique situation and it's been several years. If you do still need this, we can re-open and investigate options.
