### ISSUE TITLE
Why does wait_until use default_page_wait? Shouldn't it be default_element_wait ?

### ISSUE THREAD

**Issue by tk8817** [cheezy/page-object#347]
``` ruby
 def wait_until(timeout = PageObject.default_page_wait, message = nil, &block)
    platform.wait_until(timeout, message, &block)
  end
```

The wait_until method in page-object.rb takes 'default_page_wait' as the default timeout when an explicit value is not passed. I would expect it to be default_element_wait instead. 

``` ruby
#example setup of values
PageObject.default_element_wait = 20
PageObject.default_page_wait = 60
```
Would I be incorrect to think that wait_until is more commonly used for elements than pages, especially seeing as a wait_until should not be reached until a page has fully loaded.

**Comment by cheezy** [comment]
There are two wait_until methods - one that is on the page and another that is on each element.  They each take their corresponding wait values.
