### ISSUE TITLE
Unable to locate element using :css with version 1.1.1

### ISSUE THREAD

**Issue by simonbaire** [cheezy/page-object#352]
`invalid attribute: :css (Watir::Exception::MissingWayOfFindingObjectException)` error is displayed when using :css to locate elements. 

seems to be an issue that existed previously with watir-webdriver
https://github.com/watir/watir-webdriver/issues/241

**Comment by titusfortner** [comment]
Do you have a full stack trace for this? Are you also using :index similar to the Watir issue?

**Comment by simonbaire** [comment]
Thats all I seem to be getting. I have only used it with :css and invalid attribute: :css (Watir::Exception::MissingWayOfFindingObjectException) was the only response i got. 

it started working again when i used version 1.1.0

**Comment by titusfortner** [comment]
Run your test with ```--backtrace``` flag, or add ```$DEBUG = true``` in your code before it gets to the line that throws the error in question & post your stdout.

**Comment by simonbaire** [comment]
upon further investigation, the project i have is using a class that limits the selectors that can be used. Sorry i raised this bug in error. I will close the issue
