### ISSUE TITLE
Help monkey patching when_present into the button / link click methods.

### ISSUE THREAD

**Issue by tk8817** [cheezy/page-object#353]
Hey folks, 

I was wondering if there is a way to add an implicit wait until present for all button / link clicks that page-object handles with its 'object_name' method.

```
1 your_name # clicks the Button
```

 I have been successful in doing this for the populate_page_with method, but am having trouble in this specific instance. Why am I looking to do this? SafariDriver is giving lots of headaches due to it not waiting for page-navigation events so I am finding myself adding _element.when_present.XXXX__ all over my code. It would be cleaner and dry'r if I could hook in at the actual click method level.

```
module PageObject
  module Accessors

    def link(name, identifier={:index => 0}, &block)
      standard_methods(name, identifier, 'link_for', &block)
      define_method(name) do
        return platform.click_link_for identifier.clone unless block_given?
        self.send("#{name}_element").click
      end
    end
    alias_method :a, :link

    def button(name, identifier={:index => 0}, &block)
      standard_methods(name, identifier, 'button_for', &block)
      define_method(name) do
        return platform.click_button_for identifier.clone unless block_given?
        self.send("#{name}_element").click
      end
    end

  end
end
```

FYI on my solution for doing this in populate_page_with

```
module PageObject
    module PagePopulator

      def populate_page_with(data)
        data.each do |key, value|
          @browser.wait_until { self.send("#{key}_element").visible? }
          populate_checkbox(key, value) if is_checkbox?(key) and is_enabled?(key)
          populate_radiobuttongroup(key, value) if is_radiobuttongroup?(key)
          populate_radiobutton(key, value) if is_radiobutton?(key) and is_enabled?(key)
          populate_text(key, value) if is_text?(key) and is_enabled?(key)
        end
      end
    end
end
```

**Comment by cheezy** [comment]
@titusfortner has been talking about adding something like this to Watir.

**Comment by tk8817** [comment]
will close, have since made strides in the right direction using safer methods. thanks!
