### ISSUE TITLE
Methods for elements inside Frame/iFrame

### ISSUE THREAD

**Issue by vveliev** [cheezy/page-object#355]
PageObject::Platforms::SeleniumWebDriver::Element

methods failing for elements inside frames ...
there is no relations between element and identifiers ..... at this level ....

**Comment by tk8817** [comment]
Hi @vveliev could you please add some more details and perhaps the code that is failing in this case. Would be happy to help you out. When defining your elements inside a frame you need to use the following notation. There should be no issue in accessing the special element type methods even if they are in a frame.

```
text_field(:address, :id => 'address_id', :frame => frame)
```

**Comment by vveliev** [comment]
yes :) 

Page Code:
```rb
...
        include PageObject
        in_iframe(id: 'contact-frame') do |frame|
          text_field(:first_name, :id => 'ff_firstname', :frame => frame)
          text_field(:last_name, :id => 'ff_surname', :frame => frame)
          text_field(:email, :id => 'ff_email0', :frame => frame)
          button(:save_contact, id: 'rcmbtn104', :frame => frame)
        end

        def populate_for(key, options = nil)
          data = get_data(key, options)
          populate_page_with data
          message_to_log(data)
          page_to_log
        end
...
```
Now when you call methods directly the do work.

```
@current_page.first_name='My_name'                           # WORKING
@current_page.first_name_element.tag_name                    # not working
@current_page.populate_page_with fist_name: 'My_name'        # not working
```

The reason is when you get : 'first_name_element' it does change state back to the default before it return element "@browser.switch_to.default_content" when tag_name is executed it need to switch to frame first.

**Comment by vveliev** [comment]
I guess simple solution will be to modify populator, rescue exception. Other solution will be to some how tell PageObject::Platforms::SeleniumWebDriver::Element to switch in frame if it's available ....

**Comment by AlexisKAndersen** [comment]
@vveliev, is this still an issue in the latest version? I attempted to reproduce it, but each of those calls worked for me.
