### ISSUE TITLE
Will PageSections ever support element level waiting? 

### ISSUE THREAD

**Issue by tk8817** [cheezy/page-object#357]
Hey @daneandersen,

I know we can do a page level waits with:

``` ruby
wait_until { element.visible? }
element.action
```

But will we ever see element level waiting so we can do the more sexy:

``` ruby
element.when_visible.action 
```

I imagine there is some limitation right now which is causing PageSection elements to throw an error on this type of wait. Just wondering if that is something which we can reasonably overcome in the gem. 

Best,
Justin

**Comment by ducthanh** [comment]
of course you can pass a block or action to when_visible : your_element.when_visible.click

**Comment by tk8817** [comment]
@ducthanh , this does not work for elements inside page sections currently, you will receive an error. Page sections are different than page objects.

**Comment by mrgklwong** [comment]
@tk8817 does @page.page_section.section_element.when_present.action not work for you?

**Comment by tk8817** [comment]
@mrgklwong it did not work when doing it from inside the page section.

**Comment by tk8817** [comment]
solved with watir and new element wait logic
