### ISSUE TITLE
Text field isn't always fully populated with supplied value

### ISSUE THREAD

**Issue by dmitrym0** [cheezy/page-object#359]
I have pretty straightforward code:

  	second_new_group_dialog.group_name = future_group_name
  	second_new_group_dialog.create_group_button

backed by a page object:

```
class NewGroupDialog
	include PageObject
	text_field(:group_name, :name => "name")
```

I set `future_group_name` to a string that's 50 characters long. Occasionally though, only a part of that value is set. I guess because it's submitted too quickly and webdriver can't keep up? 

Are there any good solutions to this besides `sleep`ing?

**Comment by tk8817** [comment]
Hi @dmitrym0, 

You could try one of the following - but I am going on the assumption of load time when truly your issue could be elsewhere.

1. Utilize the initialize_page method to block actions until the page is fully loaded. This can be asserted by checking if the current_url is of the new page, and also by checking for the existing of one / some page object elements. 

2. A quicker (but more fragile) approach would be to wrap your field filling in a .when_present or .when_visible call.

```ruby
OLD
second_new_group_dialog.group_name = future_group_name

NEW
second_new_group_dialog.group_name_element.when_present.send_keys future_group_name
```

Based on the second_new_group_dialog I see in your code, it seems like you are utilizing a page section here. In which case it may be wise to wait for the page section itself to be visible

```ruby
wait_until { second_new_group_dialog.visible? }
second_new_group_dialog.group_name = future_group_name
second_new_group_dialog.create_group_button
```

**Comment by dmitrym0** [comment]
Hey @tk8817,

But that's the thing, the element is present but is only partially populated. 

So if the `future_group_name` is set to `'Very long string 1234567890'`, occasionally the field will be set to  `'Very long string 12'`. 

So the field is being set, just not fully. Does that make any sense?

**Comment by tk8817** [comment]
@dmitrym0 , now that I know it is only partially filling the start of the string, you can likely ignore my prior suggestions. Any chance you could share some more code or background on the issue?

**Comment by vveliev** [comment]
what is the browser ?! and can you manually enter entire string ?!

**Comment by dmitrym0** [comment]
Hi guys, I consulted with my coworker and it sounds like it's a webdriver issue. He can reproduce this without using PageObject -- Watir only. Looks like it's not related to you at all.

Thanks for looking into it though.
