### ISSUE TITLE
Is it safe to use sub-classing design pattern with PageObject?

### ISSUE THREAD

**Issue by tk8817** [cheezy/page-object#363]
Hi folks,

My team uses page-object to test multi-breakpoint (desktop, tablet, mobile) websites and we are looking to re-factor our codebase using the template / sub-classing pattern. We currently use a single page-object to represent all 3 breakpoints. 

In our initial testing we have seen no issues / problems but we were hoping  either @cheezy or @daneandersen could give a quick response on any pitfalls of using this pattern with page-object.

## How do we do this today?
We dynamically define our elements based on a variable ENV['BREAKPOINT'] and in our methods we do lots of ugly if / case blocking where we branch to different code depending on the value of ENV['BREAKPOINT']

### Example:
``` ruby
class AccountPcPoints
  include ::PageObject

  page_url ROOT_URL + FigNewton.partial_account_profile

    text_field(.  :points_email,             id:  'email')
    text_field(   :points_password,      id:  'password')

  case ENV['BREAKPOINT']
  when 'mobile'
    label(          :points_error_message,  class:  'account-greeting-error-msg')
  when 'desktop'
    button(       :points_link_btn,              class:  'input-pcplus-sync-button')
    label(          :points_error_message,  class:  'warning link-pc-error'')
  end

  def initialize_page
    wait_until { current_url.include?(FigNewton.partial_account_profile) }
  end

  def link_pc_plus(data)
    points_link_btn_element.when_present.click if ENV['BREAKPOINT'] == 'desktop'
    points_email_element.when_present
    populate_page_with Magic.form(data)
  end
end
```

## How do we want to do this next?
We would like to use sub-classing to increase readability and reduce cyclomatic complexity of our code. Any shared elements / classes would go into the 'root' page object, and breakpoint specifc elements & methods would go into the child page-objets. 

### Example:
``` ruby
# encoding: utf-8
class AccountPcPoints
  include ::PageObject

  page_url ROOT_URL + FigNewton.partial_account_profile

  text_field(   :points_email,                id:  'email')
  text_field(   :points_password,             id:  'password')
  
  def initialize_page
    wait_until { current_url.include?(FigNewton.partial_account_profile) }
  end

end


class AccountPcPointsMobile < AccountPcPoints
  label(        :points_error_message,     class:  'account-greeting-error-msg')

  def initialize_page
    super
  end

  def link_pc_plus(data)
    points_email_element.when_present
    populate_page_with Magic.form(data)
  end

end


class AccountPcPointsDesktop < AccountPcPoints
  button(       :points_link_btn,          class:  'mobile-pcplus-sync-button')
  label(        :points_error_message,     class:  'warning link-pc-error')

  def initialize_page
    super
  end

  def link_pc_plus(data)
    points_link_btn_element.when_present.click
    points_email_element.when_present
    populate_page_with Magic.form(data)
  end

end

```

**Comment by vveliev** [comment]
why not use @browser to make decisions ?! ...

**Comment by tk8817** [comment]
Hi vveliev, care to expand? I don't fully understand. In my mind, @browser would be the same in all cases and while you could use it to query width, it would result in the same cyclomatic complexity in the end.

**Comment by vveliev** [comment]
This does not answer your question with splitting code based on the driver.

```rb
@browser.capabilities or @current_page.browser.capabilities

@capabilities={:browser_name=>"firefox", :version=>"44.0.2", :platform=>:windows, 
:javascript_enabled=>true, :css_selectors_enabled=>true, :takes_screenshot=>true, 
:native_events=>false, :rotatable=>false, :firefox_profile=>nil, :proxy=>nil, 
"applicationCacheEnabled"=>true, "handlesAlerts"=>true, "databaseEnabled"=>true, 
"elementScrollBehavior"=>"1", "acceptSslCerts"=>true, 
"webdriver.remote.sessionid"=>"5683a46e-a787-4b02-a0d0-07350caf360a", 
"webStorageEnabled"=>true, "locationContextEnabled"=>true}
```

**Comment by tk8817** [comment]
I am not sure you understand the question being asked vveliev. this has nothing to do with the browser. Let me give you an example, if you visit Facebook on your desktop, vs on your mobile - you will be served a different design with some elements in common. This is called breakpoint code. I am looking to use page-object sub-classing to support my breakpoint code, currently we are using if blocks in a single page object.

**Comment by Cohen-Carlisle** [comment]
@tk8817 You can indeed use inheritance with the page object pattern. Though I would recommend including modules instead of inheriting from classes.

**Comment by tk8817** [comment]
Thanks for the feedback. We use modules for site wide sections like the header, footer, etc. I learned the technique from cheezy's 'Cucumber & Cheese' book. 

Do you think the module approach is ideal for 'run-specific' elements (as detailed in op)? I imagine it will result in  a case/if block to include the correct module, on each page class. 

I can see us being successful with that design but am feeling weird about it. Perhaps sub-classing is totally wrong as well, and I just have not found he right design pattern for my problem. 

Any further thoughts or suggestions? 
Thanks again! 

I will close this issue as my question on if it is supported has been answered.

**Comment by Cohen-Carlisle** [comment]
I'd act as if you were going to use inheritance, but instead of doing this:
```ruby
class Bar
  def method_a
    # ...
  end
end

class Foo < Bar
  def method_b
    # ...
  end
end
```

Do this:
```ruby
module Bar
  def method_a
    # ...
  end
end

class Foo
  include Bar

  def method_b
    # ...
  end
end
```

I generally find that modules are easier to manage than inheritance, especially as the inheritance chain gets longer.

Inheritance can work perfectly fine, too, however.

**Comment by ducthanh** [comment]
hi I would better if you can adopt cross platform solution, that means you only write the features once, but design the separated step_definition for mobile and desktop. Then you can run each you test with difference defined profiles, It really hard for you to manage the test like this for a long time because you have to take cares different UI in a single page, and even different functionalities, capabilities...etc. And I think it harder for your team to maintain the test.
 
https://github.com/calabash/x-platform-example/tree/master/features

You can see the example of using cross platform pattern above, and mix it with page object.

**Comment by tk8817** [comment]
We looked at this pattern along with the adapter pattern but it seemed overkill. The pattern forces you to duplicate ALL code, as the assumption is that each interface is fully unique.

As shown above, we only have a small difference for any given page. Some kind of inheritance / inclusion seems apt.

However, I am deeply appreciative of the feedback! It's an awesome design pattern and we DO use it for our app testing. 

Best,
Justin.

**Comment by tk8817** [comment]
@Cohen-Carlisle - we are going to use the module approach after mapping both out. Thanks for the insights.
