### ISSUE TITLE
Signal R /Watir/Pageobject/rspec

### ISSUE THREAD

**Issue by bhaskarrai** [cheezy/page-object#365]
I am trying to automate our UI testing at my work with watir/pageobject/rspec. 
One of our UI page uses signal R. When I browse to that page, my script cannot find any element that exists in that page although the elements are visible to me. Eventually I get timeout Error.
I consulted with my devloper and looks like problem is with SignalR and IEDriver interaction. Test framework freezes because page never fully loads while long polling. We have tried waiting methods too but unsuccessful to resolve the issue so far.We use IE 9 version. Is there any solution to this?

**Comment by niartseoj** [comment]
This does not sound like a page-object issue, but rather interaction between webdriver and how the signalr is implemented in your application.

Depending on how your team is using signalr the following link provides an option for changing the hub connection.
https://samritchie.net/2013/04/16/testing-a-signalr-application-using-webdriver-in-ie9/

**Comment by cheezy** [comment]
It appears that this is not a page-object issue.  I am going to close this item.  If you think there is something we should do then please reopen.
