### ISSUE TITLE
Problem with elements existence

### ISSUE THREAD

**Issue by nazaretgd** [cheezy/page-object#366]
Hi,
I'm using page objects and selenium webdriver. When I try to check the existence of an element, it always works. Even though the element doesn't exist.

This is my code
<div class="app-toolbar">

This is how I define the element div to test if ? is working.
div(:apptoolbar, :class => 'app-toolbarfasdfa')

When I use
puts page.apptoolbar

I get:
Unable to locate element: {"method":"class name","selector":"app-toolbarfasdfa"} (Selenium::WebDriver::Error::NoSuchElementError)

However when I write:
page.apptoolbar?

It continues running the rest of code
Is there any problem? Am I using the element wrongly?

Thanks in advance

**Comment by rajatthareja** [comment]
As per my understanding you are expecting page.apptoolbar? to throw error if element dos not exists. 
If I am correct then FYI
page.apptoolbar? will return true or false, it is not going to throw any error.

**Comment by nazaretgd** [comment]
Thank you very much for your soon response. I didn't know that.
I've used with: 
expect(page.apptoolbar?).to be true 

Thanks.
