### ISSUE TITLE
it there a method to locate a sibling element of div?

### ISSUE THREAD

**Issue by timsheng** [cheezy/page-object#369]
![image](https://cloud.githubusercontent.com/assets/3147281/16257032/7476324e-3888-11e6-8e57-feb10d8d1be8.png)
Firstly, I locate the `span` element  using span(:room_card,:class="room-category")
and use room_card_element.parent.parent to retrieve `div` element.
now i want to locate <ul class="room-matrix_rooms js-room-matrix-rooms"> element, how can i do?
i try to use div.element(:xpath, './following-sibling::*'), but it occurs an error:
![image](https://cloud.githubusercontent.com/assets/3147281/16257159/2482a258-3889-11e6-91db-d732edf2b85a.png)

**Comment by z41** [comment]
It is not a bug. div.element points to wrapped watir element. It is not a function for searching elements.
Try using div.elements(xpath, 'your-xpath').first

**Comment by cheezy** [comment]
If you have the div you can locate the element using `div.label_element` or locate the spans using `div.span_elements`.  You can also use a locator.  For example `div.label_element(class: 'room-card').  Reopen if you need more help.
