### ISSUE TITLE
[Request] method to set the text in a texarea element  (using the <page_object_element>=) not working

### ISSUE THREAD

**Issue by Th33x1l3** [cheezy/page-object#370]
if we have the following html

```
(...)
<textarea id="someid"></textarea>
(...)
```
and we create a page object element

`text_area(:large_text_area, :id=>'some_id')`

if we try to use the 
` large_text_area= 'some text we want to insert' `
the text is not introduced in textarea, but if we do the following:

` large_text_area_element.set  'some text we want to insert' `
then the text is inserted

Note: I'm using the new selenium webdriver (3.0 beta1)

**Comment by cheezy** [comment]
Do you get this error if you use the latest 2.X version of selenium?

**Comment by Th33x1l3** [comment]
@cheezy 

Tried with both 
 `gem 'selenium-webdriver', '~> 2.53.4' `
and just 
`gem 'selenium-webdriver' `

In both cases

 `large_text_area_element.set 'some text we want to insert'` works
`large_text_area= 'some text we want to insert` doesn't
IMHO i think it's because it's just a <textarea> element instead of the typical <input type="textarea">

**Comment by Cohen-Carlisle** [comment]
If the code is being used exactly as written (`large_text_area= 'some text we want to insert'`), this will assign a local variable `large_text_area` instead of calling the method.

To call the method, you need an explicit receiver, or, in other words `self.large_text_area = 'foo'`

**Comment by Th33x1l3** [comment]
@Cohen-Carlisle it will not. If you see cheezy uses the define_method in the module class. it will use first use the method "#{name}="

**Comment by Cohen-Carlisle** [comment]
Try running this code:
```ruby
defined?(foo) # => nil
def foo=(*args)
  puts "I just called #foo=(#{args})"
end
foo=(5) # => 5
defined?(foo) # => "local-variable"
self.foo = 10 # => prints "I just called #foo=([10])
```
Ruby interprets `foo =` as local variable assignment unless an explicit receiver is given. Most of the time this is not a problem (since usually one uses `page.foo = "bar"`), but inside the page's own class, it is. If you are defining instance methods, then `self` refers to the instance of the class, hence `self.foo = 'bar'` is what is required.

**Comment by Th33x1l3** [comment]
@Cohen-Carlisle 

```
in_frame(:name => 'mainFrame_geral') do |main_frame_geral|
      in_frame({:name => 'mainFrame'}, main_frame_geral) do |main_frame|
        text_area(:queixa_area, :id => 'input_causa_doente', :frame => main_frame)
        div(:btn_registar_queixa, :id => 'popup_ok', :frame => main_frame)

        table(:tabela_fluxogramas, :id => 'tabela_fluxogramas', :frame => main_frame)
      end
    end

 self.queixa_area_element.when_visible(10)
 self.queixa_area= queixa_str
```

tried it and it worked.
