### ISSUE TITLE
DEPRECATION WARNING *** You are calling a method named td

### ISSUE THREAD

**Issue by sri102info** [cheezy/page-object#372]
Hi @cheezy,

I'm getting the  warning when trying to access table rows from table object through its table data <td>:
table_element.td(:text, 'Problem Name').parent

**\* DEPRECATION WARNING
**\* You are calling a method named td at C:/depot/depot/depot/builds/build_16.9/ruby/ladon/lib/page_objects/athenanet/streamlined/admin/clinicals_admin/prenatal_history_admin.rb:37:in `add_prenatal_problem'.
**\* This method does not exist in page-object so it is being passed to the driver.
**\* This feature will be removed in the near future.
**\* Please change your code to call the correct page-object method.
**\* If you are using functionality that does not exist in page-object please request it be added.

**Comment by brbrr** [comment]
Is that double dots was typed intentionally?

**Comment by sri102info** [comment]
Sorry for the typo. Corrected the typo. @brbrr Thanks for notifying

**Comment by vveliev** [comment]
this have nothing to do with page object, use alternative method if it's available in selenium/watir, 'td' is not fanction of page_object and makes your code platform specific(selenium/watir)

**Comment by jkotests** [comment]
To expand on what @vveliev said, the nested element method for `td` elements is `cell_element`. You want do:

~~~~~~~~
table_element.cell_element(text: 'Problem Name').parent
~~~~~~~~

**Comment by cheezy** [comment]
No issue so I'm closing this item.  Please reopen if you disagree.
