### ISSUE TITLE
support css pseudo-selectors in page object

### ISSUE THREAD

**Issue by sri102info** [cheezy/page-object#374]
Hi Cheezy,

Right now, I'm facing an issue where an Image is loaded, which is implemented through a Pseduo-selectors like :before, :after inside div element like below, 

<div class="answer checked">APGAR SCore
:before
  <div class="read-only-note">
    Nisi aut id maiores enim delectus. Adipisci provident culpa. Et dolores et et. Qui corporis sed autx
  </div>
</div>

On inspecting that pseudo element in chrome, i found that it is in CSS styles under background with url.

Is there any way to identify the pseudo-selectors or their CSS attributes?

**Comment by z41** [comment]
Seems the only way to work with pseudo-elements is using javascript. Check an example below:
https://davidwalsh.name/pseudo-element

**Comment by jkotests** [comment]
For now, the JavaScript approach will need to be used. We can implement something here, if/when Watir adds support.
