### ISSUE TITLE
Instance-level modeling?

### ISSUE THREAD

**Issue by imjonsnooow** [cheezy/page-object#375]
From my reading of the source, it seems like `page-object` does all of its element modeling at the class level. 

It appears the `PageObject` module forces the classes that include it `extend` the `PageObject::Accessors` module. This module contains the element modeling methods, which define methods on the caller based on the element names. Since the `PageObject::Accessors` module is extended, the caller in these element name methods is also the class.

If I'm reading this correctly, that means that we can't have multiple instances of the same PageObject subclass that model an element with the same name, differently from one another. 

I've been thinking about this for a while and I'm unsure of how to do this with the current implementation. Is there a clean way to do this currently, and if not, do you have any ideas on how we could implement such a feature in `page-object`?

**Comment by daneandersen** [comment]
can you provide a code example or a failing test to represent the issue? I'm having a hard time understanding the intended code and behavior.

**Comment by imjonsnooow** [comment]
Sorry, I admit the description was a bit hand wavy and lacking a use case! Below is an example Page Object that shows the behavior I was trying to point out. 

(Of course, right after submitting this question, I remembered `singleton_class`, which appears to be a potential solution here.)

```
require 'page-object'

class ExamplePage
  include PageObject

  # ignore obviously fabricated implementation and poor code, not using page object initialize, etc
  def initialize(browser_name)
    if browser_name == 'chrome'
      self.class.div(:example1, id: 'example1')
    else
      self.class.div(:example2, id: 'example2')
    end
  end
end
```

If we attempt to create two instances of `ExamplePage`, as follows:

```
ex1 = ExamplePage.new('chrome')
ex1.example1 # defined, though it would obviously raise an error
ex1.example2 # not defined, as the example2 line did not run; this is as expected
ex2 = ExamplePage.new('firefox')
ex2.example2 # defined, though it would obviously raise an error
ex2.example1 # defined, even though we wouldn't want it to be
ex1.example2 # defined, even though we wouldn't want it to be
```

Just replacing `self.class.div` above with `self.singleton_class.div` eliminates the pollution across instances the above example suffers from.

**Comment by vveliev** [comment]
hmm..... I see this as a poor system design, or luck of my knowledge.

1. Take browser as environment config.
2. regardless of browser conceptually everything  should be the same from user point.
```rb
if @browser.name.eql?('chrome')
  self.class.div(:login_window, id: 'example1')
else
  self.class.div(:login_window, id: 'example2')
end
```

run same test cases for all browser ....make sure it's consistent. 
don't see how to write good test case using different browsers .....
same scenarios for all browsers, maybe some logic around different web-drivers

**Comment by imjonsnooow** [comment]
@vveliev: I'm not sure what you're getting at.

@daneandersen: Feel free to close this issue. I'm going to play with the `singleton_class` idea and see if it isn't too restrictive to suffice

**Comment by daneandersen** [comment]
@imjonsnooow, I think what @vveliev is trying to get at the root of what varies between browsers from the users' perspective. Do users of firefox and chrome have different ux, or are the elements for their ux located with different elements? What is the purpose of the differences between browsers?

That said, if that approach works for you, good. But if there's a need for page-object to handle something it made more difficult before, I'm open to hearing about it.

**Comment by imjonsnooow** [comment]
Ah, that makes sense. The purpose would be the ability to model cross-browser implementation differences. For example, an element might be nested differently in Chrome than in IE due to any number of design decisions or browser-related bugs/behaviors, etc. 

The goal would be to have a page object implementation which can be used safely within a single Ruby interpreter to model multiple implementations of the page based on runtime environment.

I think it would be *ideal* if page-object could support modeling at the instance level more natively, as I suspect using `singleton_class` to work around the class-level modeling will likely involve jumping through other hoops.

**Comment by vveliev** [comment]
ok so , page classes constructed before it start running the cucumber steps. When you don't have browser instance. 
You can setup browser as environment and that is one potential solution.
but you can also model around for different browsers  in the method itself.
And most likely it will be specific for selenium or watir, but i do not see problem with that....

**Comment by imjonsnooow** [comment]
@vveliev: "you can also model around for different browsers in the method itself." I agree, this would be ideal. The thing I note is that doing so still has an impact at the class level. I only see a way to call the element modeling methods (`div`, `text_field`, `button`, etc) at the class level. 

So no matter *how* we structure the modeling, it happens at the class level. There is no smooth way for instances of the class to do the modeling, instead of the class. This effectively prohibits a simplified approach to writing one class that encapsulates cross browser differences. It allows us to *write* the classes such that they observe and react to environment, but we cannot use that class to generate multiple instances (e.g., one for chrome, one for IE) from within the same Ruby interpreter instance, as they will conflict at the class level.

**Comment by daneandersen** [comment]
This sounds like it might be a job for `initialize_accessors`. It's a callback function that gets called at the end of object instantiation. You can add elements to the page at that point. I'm curious if in this way, the elements could be added to the instance directly. If the number of elements or methods grew, you might be able to move this into a couple of modules, leveraging them in the `initialize_accessors` method.

I'm not entirely sure if it will work as I'm thinking, but it's worth a shot. I'll fiddle around with it, when I get a chance.

**Comment by vveliev** [comment]
what value do you get to run all the test's from the same ruby VM, you are trying to reuse same cucumber feature. 
Ex.
you have 4 browsers. (use script/jenkins or what ever) 
start 4 independent processes for each browser  with ENV['BROWSER'] = 'remote ff/chrome/ie/safary'
you get buck 4 reports and i see no problem how this would not work .... if you make decision at the time when you have browser instance or if you class have been constructed for one particular browser 


I'm sure there is some way to do meta programming on meta programming, i just don't see the reason why.

**Comment by imjonsnooow** [comment]
@daneandersen: Thank you -- I'll start looking into that approach too!

@vveliev: Thank you for your thoughts! :) However, you've made assumptions about my use case that are non-applicable. I've not mentioned Cucumber at all, nor have I said that I'm necessarily using these page objects to power tests. At its core, `page-object` is a tool for modeling. We build a model of our application as **Page Objects**, and people mainly use such a model to power tests; I may use it to power other things!

`page-object` class-level modeling restricts its flexibility. Of course we can do IPC with separate processes...but should we have to? That's forcing a decent amount of overhead and limiting possibilities for usage. Maybe rectifying this design issue isn't high priority because people tend to use `page-object` the way you're describing, and if so, that's fine! :) But the overall question isn't "how do you currently work around this?", but rather "is there a reason that page-object works this way and if not, can we fix it?"

**Comment by cheezy** [comment]
I am going to go ahead and close this issue but feel free to reopen if you wish to continue the discussion.

**Comment by imjonsnooow** [comment]
Absolutely reasonable! 👍 Just leaving this comment to document for anybody with similar questions down the line:

I was able to solve this by running all of my `page-object` modeling calls on the `singleton_class` of instances. Code sample:

```ruby
require 'page-object'

class InstancePageObject
  attr_reader :browser

  # browser must be a watir browser instance.
  def initialize(browser)
    @browser = browser

    singleton_class.send(:include, PageObject)
    initialize_browser(@browser) # shortcut the PageObject initializer

    # model page elements in context of the singleton class to avoid collisions in 
    # instance-level modeling differences when using the shared parent class.
    model_html(singleton_class)
  end

  # Define HTML elements on this page.
  # @param [Class] target_class The class to execute our page object modeling on
  def model_html(target_class)
    target_class.text_field(:name, id: 'locator')
  end

  # Example usage of element
  def put_thing_in_name_field
    self.name = 'thing'
  end
end
```
