### ISSUE TITLE
DEPRECATION WARNING *** You are calling a method named ul

### ISSUE THREAD

**Issue by jordiponsllaurado** [cheezy/page-object#376]
Hi,

I'm getting the warning when trying to access 'ul':

`block_element.ul(index: position).lis`
The warning looks like:
```
*** DEPRECATION WARNING
*** You are calling a method named ul at /Users/jordipons/Documents/repos/repo_one/block.rb:59:in `block_choices'.
*** This method does not exist in page-object so it is being passed to the driver.
*** This feature will be removed in the near future.
*** Please change your code to call the correct page-object method.
*** If you are using functionality that does not exist in page-object please request it be added.
```

I've tried to use this: `block_element.unordered_list(index: position).lis` but then I get the following error:
```
NoMethodError: undefined method `unordered_list' for #<Watir::Div:0x007ffe1dad6880>
```

How can I solve the warning?

Thanks

**Comment by sri102info** [comment]
Hi @jordiponsllaurado ,

lis is not supported in page-object. You can try using,
block_element.unordered_list(index: position).list_item_elements

Let me know if the issue is solved or not.

**Comment by jordiponsllaurado** [comment]
I moved the unordered_list outside the method, so at the beginning of the class and now it works
