### ISSUE TITLE
FF reporting cheezyworld.com as an attack page (fyi)

### ISSUE THREAD

**Issue by timrsfo** [cheezy/page-object#377]
This web page at www.cheezyworld.com has been reported as an attack page and has been blocked based on your security preferences.

Attack pages try to install programs that steal private information, use your computer to attack others, or damage your system.

Some attack pages intentionally distribute harmful software, but many are compromised without the knowledge or permission of their owners.

clicked on link on your main page and got the above message,
is it still valid link? Should the warning be ignored?
FF 48, Ubuntu 14.04

**Comment by timrsfo** [comment]
Getting similar msg from Chrome

The site ahead contains malware

Attackers currently on www.cheezyworld.com might attempt to install dangerous programs on your computer that steal or delete your information (for example, photos, passwords, messages, and credit cards).
  Automatically report details of possible security incidents to Google. Privacy policy

**Comment by cheezy** [comment]
I can't find the issue.  Been working on it for a while :(

**Comment by timrsfo** [comment]
are you saying the problem doesn't happen in your setup, or it does but you haven't found a reason why?  I get the same thing from my windows 7 box using FF

**Comment by cheezy** [comment]
I am saying that I cannot figure out why it is flawed as malware.  I could use some help on this one.

**Comment by cheezy** [comment]
I'm closing since this is not a page-object issue.

**Comment by timrsfo** [comment]
I was able to get to it on my android phone/chrome without the message. it probably has an older browser version. Looks like there is nothing new on cheezyworld since 2012. If you change your mind and can think of anything you want me to try, let me know
