### ISSUE TITLE
How do we want to handle watir_webdriver --> watir?

### ISSUE THREAD

**Issue by tk8817** [cheezy/page-object#378]
Hey @cheezy and @daneandersen,

I have a fork up investigating the changes required to support the 'new' watir-webdriver repo structure and so far I have only found one breaking change (detailed below). However, I wanted to ask what strategy you guys think is best for updating page-object.
1. Add the 'new' `watir` repo as a new platform, leaving `watir-webdriver` in-tact.
2. Deprecate `watir-webdriver` and replace it outright with `watir` in the existing platform. 

In regards to the errors I encountered making the switch: 
1. `watir/extensions/alerts` has been depricated and is now located at `watir/alert`
   I made the change but there is an error on the watir side noting `uninitialized constant Watir::Alert::EventuallyPresent (NameError)`. PageObject runs with this require commented out, need to investigate how they have evolved alert handling.

**Comment by titusfortner** [comment]
EventuallyPresent shouldn't result in an error right now, but I'm hoping to make a more significant change to how Watir supports waiting in general before 6.0 is released. 

I can help make sure that this gem works with where things end up.

**Comment by cheezy** [comment]
We will work on supporting Watir as soon as the 6.0 release is out.

**Comment by cheezy** [comment]
I am going to close this issue.  I will work with @titusfortner when Watir 6 comes out to provide support with page-object.
