### ISSUE TITLE
How to access elements inside an Iframe which is inside a div element

### ISSUE THREAD

**Issue by sri102info** [cheezy/page-object#379]
Consider having two different div elements in DOM based on their visibility. Inside the two div elements, we having a separate IFrame (All elements for IFrame are same under both div). 
```
<div id='breif'>
  <iframe id='ob_brief'>
    <input></input>
    <table></table>
  </iframe>
</div>
<div id='intake'>
  <iframe id='ob_intake'>
    <input></input>
    <table></table>
  </iframe>
</div>
```

I thought of getting the same page object element for div based on their visibility, like

```
div(common_div) do |page|
  if page.div_element(id: 'brief', frame: fr_main).visible?
    page.div_element(id: 'brief', frame: fr_main)
  elsif page.div_element(id: 'intake', frame: fr_main).visible?
   page.div_element(id: 'intake', frame: fr_main)
  end
end
```

@cheezy , Is there any way to access an Iframe inside the div element?

**Comment by cheezy** [comment]
@sri102info  I'm not sure I following the structure.  You have two divs and there are two iframes inside each div?  You want to access items in the iframes?

**Comment by kierr** [comment]
I am attempting to do something similar, @cheezy. Perhaps you can assist.

I am using `in_frame`.... but my `frame` is within a `div`, both of which are in a `form`:

```
<form>
  <div id='frame-wrapper'>
    <iframe src="http://domain.com/login/randomstring"></iframe>
  </div>
</form>

So I don't have any selectors to identify the frame by. I suspect I could just use `index`, but annoyingly this frame switches position so I don't think that will work reliably.

Thanks

**Comment by AlexisKAndersen** [comment]
Is this a technical issue with not being able to access the frames, or with needing a better way to deal with whether frames are or are not visible?

@sri102info, @kierr, if either of you are still experiencing this problem, feel free to reopen the issue and expand on the problem.
