### ISSUE TITLE
Selenium 3 support for execute_script

### ISSUE THREAD

**Issue by phebus** [cheezy/page-object#383]
They changed `executeScript` in the Selenium::WebDriver::Remote::Bridge to `execute_script` for the Ruby Webdriver implementation. This breaks various element methods in **lib/page-object/platforms/selenium_webdriver/element.rb**

Currently am able to work around it with monkey patching an alias in

**Comment by vveliev** [comment]
Selenium 3 in beta, so not sure if this is na issue yet.

**Comment by titusfortner** [comment]
I'll try to take a look at Se 3 & Page Object soon. Those Bridge methods are private API and shouldn't be used directly. The right answer is to use the driver to access them, but it looks like that might be a significant change to PO implementation.

**Comment by phebus** [comment]
Yeah this is definitely meant as more of a "heads up" than "need now" kind of thing. I'd been playing with the beta, and Simon mentioned beta 4 was almost ready and they were close to the end of blocking issues. This looks like a purposeful change on their end considering it's more Ruby-like. Thanks for looking!

**Comment by titusfortner** [comment]
Beta 4 has been released, and the proper 3.0 release is pretty much just waiting on Simon to untangle some of the server logging. Many of the options and methods in the Ruby portion of Selenium 2.x were an odd mix of symbols, strings, snake case and camel case. I went through and changed things trying to make it all more consistent.

**Comment by cheezy** [comment]
I do not see where executeScript is called.  I only see execute_script.  Did somebody else fix this?

**Comment by titusfortner** [comment]
Yes, that was part of the Travis PR you merged of mine.

**Comment by cheezy** [comment]
Ok.  Then I think I can close this issue as I will be releasing it in the next couple of days.
