### ISSUE TITLE
Misbehaves with watir-webdriver 0.9.2 and 0.9.3

### ISSUE THREAD

**Issue by sciros** [cheezy/page-object#384]
With watir-webdriver 0.9.1, everything works. With the latest two versions (they are fairly recent, from late summer), running Cucumber tests with page-object yields a lot of these:

wrong constant name Watir::Locators::Element::Validator (NameError)

They seem to happen as soon as a page method is called.

Actually... this is probably the tip of the iceberg, as it looks like the watir-webdriver project is now Watir 6.

**Comment by cheezy** [comment]
What is currently in git should work with the latest.  All specs and features pass.  Can you give it a try?

**Comment by cheezy** [comment]
I am using with these versions of 0.9.3 so I am going to go ahead and close this issue.  If you are still having issues then please reopen and provide details.
