### ISSUE TITLE
Uninitialized constant MyPage::PageObject (NameError)

### ISSUE THREAD

**Issue by Portalboy** [cheezy/page-object#385]
The following syntax:
```
require 'page-object'
class MyPage
  include PageObject
end
```
Returns this error:
``Uninitialized constant MyPage::PageObject (NameError)``

I'm on ``Ruby 2.3.1p112 (2016-04-26 revision54768 [x64-mingw32])``
with ``page-object 1.2.0``
I've also tried from various parts of my test suite (using `RSpec 3.5.0`)

**Comment by Portalboy** [comment]
Also, my first reaction was that I must have forgotten to install page-object based on the error, but I did `gem install page-object` again to make sure, and sure enough `gem list page-object` returns page-object 1.2.0`

**Comment by joesho112358** [comment]
I have a similar set up, ran the following, and no problems. How are you calling it? Does not look like a page-object issue to me though.

```ruby
require 'page-object'
require 'watir-webdriver'

class MyPage
  include PageObject
end

b = Watir::Browser.new
MyPage.new b
b.close
```

**Comment by Portalboy** [comment]
It was some voodoo I was doing with ``if __FILE__ == $0``. It was erroring out when I tried to initiate the file directly because it's part of an RSpec suite, but it wasn't triggering the `require` when I used RSpec to initiate it.
