### ISSUE TITLE
Blog post marked as malicious

### ISSUE THREAD

**Issue by Portalboy** [cheezy/page-object#386]
References to the blog post serving as the 'inspiration for this gem' are flagged by Malwarebytes as malware distribution nodes. The website hosting that post may have been compromised.

**Comment by cheezy** [comment]
I have tried to find out why this is happening.  Anybody with experience in this area wanna help?

**Comment by Portalboy** [comment]
Typically these flags happen when the given site has been reported as having distributed malware to multiple clients. It's possible the blog was compromised and an attack was mounted on it, perhaps one that can't be detected by a client, such as an XSS attack. 
This is why https is becoming more of a standard. In standard unsecured http, there is no way of knowing if the site has been modified. 

Anyways, I believe these sorts of alerts are usually from a website that has already distributed malware rather than one with proper conditions. 
I don't claim to be a security expert and I may be wrong on one or more of these points.

**Comment by cheezy** [comment]
I'm going to close this since it is not really about the page-object gem.
