### ISSUE TITLE
page-object-1.2.2 still has dependencies to watir-webdriver

### ISSUE THREAD

**Issue by emereyd** [cheezy/page-object#397]
hi, I've followed the instructions according to commits from Nov 20th 2016. (i.e removing all references to `watir-webdriver`)

However, there still looks like there is a reference to  `watir-webdriver-0.9.3` somewhere in page-object gem that I can't source.

Steps to reproduce:
1.Force uninstall watir-webdriver and page-object
```
gem uninstall watir-webdriver
Continue with Uninstall? [yN]  y
gem uninstall page-object
Successfully uninstalled page-object-1.2.2

```
2. Install page-object
```
 gem install page-object
 ```
 output:
```
Fetching: watir-webdriver-0.9.3.gem (100%)
Successfully installed watir-webdriver-0.9.3
Fetching: page-object-1.2.2.gem (100%)
Successfully installed page-object-1.2.2
Parsing documentation for watir-webdriver-0.9.3
Installing ri documentation for watir-webdriver-0.9.3
Parsing documentation for page-object-1.2.2
Installing ri documentation for page-object-1.2.2
Done installing documentation for watir-webdriver, page-object after 4 seconds
2 gems installed
```

Please help! Having watir and watir-webdriver in our eco-system is causing lots of runtime issues and preventing us from running our tests.

Thanks in advance.

**Comment by brbrr** [comment]
Try to run your tests with `bundle exec` and make sure you dont have `watir-webdriver` in your gemfile. if youll search for `watir-webdriver` in source code - you'll not find anything.

**Comment by emereyd** [comment]
Aha! Your edited suggestion did the trick! 
Much appreciated.
