### ISSUE TITLE
Instead of passing arguments into #wait_until_present method, use keywords

### ISSUE THREAD

**Issue by dhananjay19** [cheezy/page-object#398]
*** DEPRECATION WARNING
*** You are calling a method named wait_until_present at C:/workpace/features/step_definitions/outbound_payments_create.rb:16:in `block in <top (required)>'.
*** This method does not exist in page-object so it is being passed to the driver.
*** This feature will be removed in the near future.
*** Please change your code to call the correct page-object method.
*** If you are using functionality that does not exist in page-object please request it be added.
Instead of passing arguments into #wait_until_present method, use keywords

**Comment by titusfortner** [comment]
Take a look at the Watir 6.0 FAQ on [using keywords instead of arguments](http://watir.github.io/watir-6-faq/#G)

**Comment by cheezy** [comment]
The release coming out shortly (possibly tomorrow) has support for watir 6.

**Comment by dhananjay19** [comment]
Sounds great, Thanks Cheezy

**Comment by cheezy** [comment]
2.0 was released.  This should resolve this issue.
