### ISSUE TITLE
indexed_property count?

### ISSUE THREAD

**Issue by soumyaray** [cheezy/page-object#401]
I've got a table of content that I am representing as an `indexed_property`.  I'd like to get a count of how many rows are in the table (i.e., how many sets of elements in the indexed property).  Is there such a way to count collections?

**Comment by soumyaray** [comment]
Just want to add that I realize that I can independently add a table element, and get a count using `.rows`. But I am wondering if we can do that on `indexed_property` as well (e.g., if our data is not in a table).

**Comment by AlexisKAndersen** [comment]
There is not currently any built in method of getting a count for indexed_properties. While it is theoretically possible to implement the methods required to get the count, it would work in only certain circumstances, and wouldn't be in the spirit of indexed properties' flexibility. 

In the case of not using a table, page_sections is probably most closely what you're needing. https://github.com/cheezy/page-object/wiki/Page-Sections#representing-collections-of-related-elements

If you feel a count for indexed properties is still required after that, feel free to open a feature request issue.
