### ISSUE TITLE
Selenium version.

### ISSUE THREAD

**Issue by vveliev** [cheezy/page-object#404]
Hello, I thinks it's nice to follow with updates to the libs and everything. 

But I think it's a bit to early for switching to Selenium 3.0 as firefox webdriver is not working well with certs just yet. 

So maybe have an ability to say what version of selenium will be used with page_object.

I know that no one forcing me to update but just as a thought.

**Comment by titusfortner** [comment]
You can still use legacy Firefox with Selenium 3. Just pass in `marionette: false` along with your capabilities.
