### ISSUE TITLE
DEPRECATION WARNING: You are calling a method named tbody

### ISSUE THREAD

**Issue by DragonSlay3r** [cheezy/page-object#407]
Hi,

I am getting this warning when using table_element.tbody.rows.find {...}. I looked thro' the documentation and couldn't find what the issue is. can this method be added to driver?

`*** DEPRECATION WARNING
*** You are calling a method named tbody at (byebug):1:in `block in get_table_row'.
*** This method does not exist in page-object so it is being passed to the driver.
*** This feature will be removed in the near future.
*** Please change your code to call the correct page-object method.
*** If you are using functionality that does not exist in page-object please request it be added.`

**Comment by Castone22** [comment]
This function should already exist if I'm grocking what you want to do. 

If you wish to check if a given row of the table contains text you can just do something along the lines of 

```ruby
table_element.each { |row| ... }
```

You can also call 

``` ruby
table_element['some text']
#note iirc you could call .parent or .parent_element to grab the row element the cell exists in but I'm not 100% on that one...
```

To retrieve a cell element in a table containing "some text"

The wiki page on here contains some information on this functionality under the elements section.

**Comment by Castone22** [comment]
upon closer inspection, table_element['some text'] will return the row element containing that text so the parent_element is unnecessary.

**Comment by cheezy** [comment]
you can simply call `find` on the `table_element` directly.
