### ISSUE TITLE
unable to read text from a table using page object - undefined method `text' for 0:Fixnum (NoMethodError)

### ISSUE THREAD

**Issue by harimadusumilli** [cheezy/page-object#409]
browser.table(:id => "resultList").rows[1][1].text

I am able to see the output of the above in irb and when I do a puts also its getting me the result.

When I am using the pageobject for getting the row count, I am able to get the value as follows 
row_count = site_search_results_table_element.rows

when I use the following :

site_search_results_table_element.rows[1][1].text inside the class for e.g :

class VMI_Create_order_Find_sitePageObject
	 include PageObject

text_field(:keyword_search,:name => "searchText")
button(:search,:value => "SEARCH")
table(:site_search_results_table,:id => "resultList")

def locate_site(site_name)

row_count = site_search_results_table_element.rows
puts "row count : #{row_count}"
puts "#{@browser.table(:id => "resutList").rows[1][1].text}" # this works fine 
puts "#{site_search_results_table_element.rows[1][1].text}" # I get the following error :undefined method `text' for 0:Fixnum (NoMethodError)

for row_index in 1..row_count - 1
	site_name_value = site_search_results_table_element.rows[row_index][1].text
	if (site_name_value.eql?(site_name))
		
		return true
	end
end

return false

end

end

I am not sure as to what the issue is, in earlier versions of watir I did not see this issue, any help is appreciated.

**Comment by cheezy** [comment]
The code you need to have is `site_search_results_table_element[1][1].text`.  In page-object the `rows` method returns the number of rows.  The {name}_element method returns an instance of the Table class which has the indexing methods directly.
