### ISSUE TITLE
Do you have something similar like the "page-object-gem" available for Java selenium framework?

### ISSUE THREAD

**Issue by ndluog** [cheezy/page-object#411]
In the Java Selenium framework, automation testers have been using Page Object Model (POM) to organize their objects/elements in separate classes, and store all related methods under the same class. That is, however, not the same as what page-object-gem can provide. I have been using page-object-gem in my ruby/water/rspec framework for two years (and loving it), now I need to move on to implement a Java Selenium framework. I would love to know if something like page-object-gem exists in Java. This way I don't have to code the generic methods like clickButton, getTextOfElement, isElementExist, etc, etc

**Comment by vveliev** [comment]
check this project
https://github.com/atinfo/awesome-test-automation

**Comment by cheezy** [comment]
I have a simple page-object like framework that I use when I teach classes in Java.  It's not in git but I'd be happy to share it with you if you want.

**Comment by ndluog** [comment]
Jeff,

That would be wonderful. Thank you. Your the best.

I have been in the Ruby/Page-object-gem world for a few years. Writing automation tests are a breeze thanks to page-object-gem. I am now with a company who is a Java shop. We have to make methods for every thing: click, getValue, etc, etc. 

Thanks for your invention of page-object-gem, which made our lives easier.

Lian

**Comment by cheezy** [comment]
Here it is.
[JavaTutorial.zip](https://github.com/cheezy/page-object/files/821451/JavaTutorial.zip)
