### ISSUE TITLE
Is the HTML object type 'nav' modeled? 

### ISSUE THREAD

**Issue by Githraine** [cheezy/page-object#413]
I have a page with a `<nav>` tag block I want to interact with.  Can I do that within Pageobjects? Or do I have to fall back on the Browser object and raw Watir?

**Comment by cheezy** [comment]
It is covered.  Look at PageObject::LocatorGenerator and you will see a list of BASIC_ELEMENTS. nav is included.
Then look at PageObject::Accessors line 1095 as in git and you will see where that list is used to generate methods.

-Cheezy

**Comment by Githraine** [comment]
Thank you!
