### ISSUE TITLE
2.1 introduced uninitialized constant Watir (NameError)

### ISSUE THREAD

**Issue by visko83** [cheezy/page-object#414]
I have upgraded to page-object 2.1 and I faced this issue:
```
/Users/visko/.rvm/gems/ruby-2.3.3/gems/watir-6.2.0/lib/watir/extensions/select_text.rb:1:in `<top (required)>': uninitialized constant Watir (NameError)
	from /Users/visko/.rvm/gems/ruby-2.3.3/gems/page-object-2.1/lib/page-object/elements/element.rb:2:in `require'
	from /Users/visko/.rvm/gems/ruby-2.3.3/gems/page-object-2.1/lib/page-object/elements/element.rb:2:in `<top (required)>'
	from /Users/visko/.rvm/gems/ruby-2.3.3/gems/page-object-2.1/lib/page-object/elements.rb:29:in `require'
	from /Users/visko/.rvm/gems/ruby-2.3.3/gems/page-object-2.1/lib/page-object/elements.rb:29:in `<top (required)>'
	from /Users/visko/.rvm/gems/ruby-2.3.3/gems/page-object-2.1/lib/page-object/widgets.rb:1:in `require'
	from /Users/visko/.rvm/gems/ruby-2.3.3/gems/page-object-2.1/lib/page-object/widgets.rb:1:in `<top (required)>'
	from /Users/visko/.rvm/gems/ruby-2.3.3/gems/page-object-2.1/lib/page-object.rb:11:in `require'
	from /Users/visko/.rvm/gems/ruby-2.3.3/gems/page-object-2.1/lib/page-object.rb:11:in `<top (required)>'
	from my_test.rb:1:in `require'
```

I don't use Watir on the project but Selenium only. Please let me know if further details are required.
Downgrading to 2.0.0 resolved the problem, could you please check?

**Comment by cheezy** [comment]
I’m looking into it now.

**Comment by cheezy** [comment]
Peter,

Can you try to remove the require statement that is on line 2 of lib/page-object/elements/element.rb and see if that resolves the problem?

-Cheezy

**Comment by cheezy** [comment]
Peter,

I have not been able to reproduce the issue but I think I have it fixed.  Can I provide you with a version of the gem and have you test it out to ensure it resolves your issue?

-Cheezy

**Comment by visko83** [comment]
hi Cheezy,

Thanks for the reply. Removing 
`require 'watir/extensions/select_text'`
from lib/page-object/elements/element.rb:2 did not resolve the issue:
```
/Users/visko/.rvm/gems/ruby-2.3.3/gems/watir-6.2.0/lib/watir/elements/html_elements.rb:3:in `<module:Watir>': uninitialized constant Watir::Element (NameError)
	from /Users/visko/.rvm/gems/ruby-2.3.3/gems/watir-6.2.0/lib/watir/elements/html_elements.rb:2:in `<top (required)>'
	from /Users/visko/.rvm/gems/ruby-2.3.3/gems/page-object-2.1/lib/page-object/elements/table_row.rb:1:in `require'
```

Yes I can try the fixed version, I would be happy to test it :).

**Comment by cheezy** [comment]
Give this version a try.
[page-object-2.1.1.gem.zip](https://github.com/cheezy/page-object/files/824926/page-object-2.1.1.gem.zip)

**Comment by visko83** [comment]
It looks fine, could you please proceed with release? Thank you very much for your efforts!

**Comment by cheezy** [comment]
It's released
