### ISSUE TITLE
wrong number of arguments (0 for 1..2) (ArgumentError)

### ISSUE THREAD

**Issue by jmtabares** [cheezy/page-object#416]
using Ruby 2.0.0
watir 6.2.0
page-object 2.0.0
fig_newton

wrong number of arguments (0 for 1..2) (ArgumentError)
/Users/jair/.rvm/gems/ruby-2.0.0-p648/gems/page-object-2.0.0/lib/page-object.rb:78:in `initialize'
/Users/jair/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:13:in `initialize'
/Users/jair/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/psych/nodes/node.rb:35:in `new'
/Users/jair/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/psych/nodes/node.rb:35:in `to_ruby'
/Users/jair/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/psych.rb:130:in `load'
/Users/jair/Dev/qa-automation/agroptima-automation/features/support/pages/main_page.rb:10:in `<class:MainPage>'
/Users/jair/Dev/qa-automation/agroptima-automation/features/support/pages/main_page.rb:6:in `<top (required)>'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/bin/cucumber:23:in `load'
/Users/jair/.rvm/gems/ruby-2.0.0-p648/bin/cucumber:23:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'

**Comment by cheezy** [comment]
Can you show me the code for main_page.rb - specifically around line 10?

**Comment by yudi2312** [comment]
Hi Jeff, Any update on this?

**Comment by AlexisKAndersen** [comment]
Without seeing the code, all I can imagine is to make sure you're passing the watir browser when initializing your page. Or preferably use the built in navigation methods `visit` and `on`. If these don't address your problem feel free to reopen and provide the code being executed that's failing.
