### ISSUE TITLE
Error with Cucumber and Selenium Webdriver

### ISSUE THREAD

**Issue by richdownie** [cheezy/page-object#421]
I'm using Page-Objects with Cucumber + Selenium-WebDriver and started seeing this Error in version 2.1

<img width="994" alt="screen shot 2017-03-21 at 7 55 37 pm" src="https://cloud.githubusercontent.com/assets/3307/24176145/a7b75d4a-0e70-11e7-8f16-732f1ebe4543.png">

Here is my Cucumber features/support/env.rb
<img width="387" alt="screen shot 2017-03-21 at 7 55 26 pm" src="https://cloud.githubusercontent.com/assets/3307/24176188/e0d296e4-0e70-11e7-8d72-20e75032e3d2.png">

Any suggestions on how I can resolve this?

Thanks
Rich

**Comment by vveliev** [comment]
use 
```rb
div_element 
button_element
text_field_element
.
.
.

```

**Comment by cheezy** [comment]
Can you show the code for your SingIn page?

**Comment by richdownie** [comment]
Sure
![screen shot 2017-03-22 at 10 43 13 am](https://cloud.githubusercontent.com/assets/3307/24203539/6bc77bc2-0eec-11e7-857f-1c1fc2a784c0.png)

**Comment by richdownie** [comment]
Strange that it is trying to initialize Watir?  I'm not using Watir and do not have require 'watir' anywhere in my repo. 🤔

`rich:triage_selenium_suite richdownie$ cucumber features/appliance_features/authentication.feature:8
uninitialized constant Watir (NameError)
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/watir-6.0.3/lib/watir/extensions/select_text.rb:1:in `<top (required)>'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/page-object-2.1/lib/page-object/elements/element.rb:2:in `require'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/page-object-2.1/lib/page-object/elements/element.rb:2:in `<top (required)>'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/page-object-2.1/lib/page-object/elements.rb:29:in `require'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/page-object-2.1/lib/page-object/elements.rb:29:in `<top (required)>'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/page-object-2.1/lib/page-object/widgets.rb:1:in `require'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/page-object-2.1/lib/page-object/widgets.rb:1:in `<top (required)>'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/page-object-2.1/lib/page-object.rb:11:in `require'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/page-object-2.1/lib/page-object.rb:11:in `<top (required)>'
/Users/richdownie/triage_selenium_suite/features/support/env.rb:3:in `require'
/Users/richdownie/triage_selenium_suite/features/support/env.rb:3:in `<top (required)>'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/richdownie/.rvm/gems/ruby-2.2.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/richdownie/.rvm/gems/ruby-2.2.0/bin/cucumber:23:in `load'
/Users/richdownie/.rvm/gems/ruby-2.2.0/bin/cucumber:23:in `<main>'
/Users/richdownie/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/richdownie/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
rich:triage_selenium_suite richdownie$`

**Comment by jkotests** [comment]
In version 2.1, the Page-Object gem was refactored to only use Watir internally. When you use Selenium, initializing the page object actually converts the `Selenium::WebDriver::Driver` to a `Watir::Browser`. In short, you do need to start ensuring you have Watir installed.

These changes also causing the exception with `@browser.first(id: 'new_user').submit`.
`@browser` is now the `Watir::Browser`, rather than the `Selenium::WebDriver::Driver` it used to be.

It does not appear that the Page Object stores the original object used to initialize the page - ie there is no direct access to the driver. Instead, you will need to access the underlying Selenium driver by calling the `Watir::Browser#driver` method:

~~~~~~~~
def button
  @browser.driver.first(id: 'new_user').submit
end
~~~~~~~~

This doesn't seem ideal for those using Selenium-WebDriver. However, I don't know if the backwards incompatibility is intentional or not.

**Comment by richdownie** [comment]
Ok, @browser.driver.first(id: 'new_user').submit is working!  Thanks!

**Comment by titusfortner** [comment]
Or, you can use the Watir syntax to shorten it to: `@browser.element(id: 'new_user').submit`
