### ISSUE TITLE
page-object drop target for watir-webdriver method drag_and_drop_on() fails check for Watir::Element

### ISSUE THREAD

**Issue by chrismcmahon** [cheezy/page-object#422]
Apropos of http://www.rubydoc.info/gems/watir-webdriver/Watir%2FElement:drag_and_drop_on

Code like this using the _element appending aspect of page-object for both source and target

```ruby
page.drop_thing_element.drag_and_drop_on page.drop_target_element
```
yields an error "execpted Watir::Element, got #<Watir::Div: located: false; {:id=>"liveDropTarget", :tag_name=>"div"}>:PageObject::Elements::Div (TypeError)" (yes the misspelling is real) for the *target* element.
But dropping the '_element' part like so

```ruby
page.drop_thing_element.drag_and_drop_on page.drop_target
```
yields an error "execpted Watir::Element, got "":String (TypeError)"

page-object seems to be running afoul of this check in watir https://github.com/watir/watir/blob/472732a3b7899fd6595e966997b3a42922462fbb/lib/watir/elements/element.rb#L631 (the misspelling made finding that easier than it would otherwise have been)

Note that the draggable element seems to be handled correctly; the Element vs. Div problem seems to be in the drop target only.

**Comment by chrismcmahon** [comment]
Any idea how to get around this? I've surfed the p-o code and nothing jumped out at me.

**Comment by jkotests** [comment]
Unless I missing something, Page-Object has not yet implemented `drag_and_drop_on`. It is an outstanding request - see Issue #184.

Until it is implemented, the drop target will need to be a Watir::Element, which is accessed via the `element` method:

~~~~~~~~
page.drop_thing_element.drag_and_drop_on page.drop_target_element.element
~~~~~~~~

**Comment by vveliev** [comment]
here is the sample code that I have and it's working

```rb

        div(:message_render, id: 'message_render')

        def snippet_by_name(name)
          span_elements(class: 'section-name').each do |snippet|
            return snippet if snippet.text.eql?(name)
          end
        end

        def add_section_by_name(name)
          self.snippet_by_name(name).element.drag_and_drop_on(message_render_element.element)
          wait_for_ajax(timeout = 30, message = 'Ajax timeout 378564')
        end
```

**Comment by jkotests** [comment]
To reproduce, given the HTML:

~~~~~~~~
<div id="a">asdf</div>
<div id="b">bvbn</div>
~~~~~~~~

Then the error will happen when doing: 

~~~~~~~~
class MyPage
  include PageObject

  div :a, id: 'a'
  div :b, id: 'b'
end

page = MyPage.new(browser)
page.a_element.drag_and_drop_on(page.b_element)
~~~~~~~~

Similar to #execute_script, we'll need to define #drag_and_drop_on such that it extracts the underlying Watir::Element.
