### ISSUE TITLE
`platform` variable is nil when calling _element method on page object

### ISSUE THREAD

**Issue by mbrodie617** [cheezy/page-object#423]
```
user$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
```

Below is a summary of my PageObject model

```ruby
require 'page-object'
class GreatObjectsPage
  include PageObject
  attr_accessor :value

  label(:topicHeader, :css => "[data-test-id=\"#{@value}\"] .category-label")

  def initialize(value, *args)
    puts args.inspect
    @value = value
  end
end
```

When initializing a new GreatObjectsPage from elsewhere, like so:
```ruby
Then(/^user verifies X "(.*)" object "(.*)" contains text "(.*)"$/) do |topic, object, value|
  t = GreatObjectsPage.new topic
  obj = t.topicHeader_element
end
```

...the `t.topicHeader_element` call fails with the following trace:
```
undefined method `label_for' for nil:NilClass (NoMethodError)
```

Following this down through the debugger lands me on line `1109` of `page-object-2.1.1/lib/page-object/accessors.rb`, where I see the call `platform.send(method, identifier.clone)`, but `platform` is set to `nil` and I can't figure out why, what it is, or what it should be set to. I wasn't able to use the debugger to determine how we arrived at the `standard_methods` method in `accessors.rb`, nor how the `method` variable was set to `:label_for` in that scope. 

Any help would be much appreciated.

**Comment by cheezy** [comment]
PageObject already has a default constructor that takes the Watir::Browser object.  You have overridden that method and that is why you are getting the error.  Take a look at the Factory methods.  They will provide a simpler way to accomplish what you want.

https://github.com/cheezy/page-object/wiki/Creating-and-using-page-objects <https://github.com/cheezy/page-object/wiki/Creating-and-using-page-objects>

-Cheezy

**Comment by AlexisKAndersen** [comment]
It's also worth noting there are callback methods like `initialize_page` you can define to handle any other initialization you need outside of what page object performs.
