### ISSUE TITLE
JavascriptFrameworkFacade.framework  support for multiple frameworks.

### ISSUE THREAD

**Issue by vveliev** [cheezy/page-object#426]
Running in to the problem when i set : 
```rg
JavascriptFrameworkFacade.framework=:jquery
```
This is working for all pages but one , that for whatever reason not using Jquery.

is there way to ignore framework or have different one for single page ?!

**Comment by vveliev** [comment]
jQuery is not used on one page .....

```
      unknown error: jQuery is not defined
        (Session info: chrome=58.0.3029.110)
        (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 3.13.0-37-generic x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 4 milliseconds
      Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
```

**Comment by AlexisKAndersen** [comment]
I've run into this same issue before. Because the javascript framework code is only invoked when calling `wait_for_ajax`, I just reimplemented that method on the page that didn't use the framework, but as a no-op.

**Comment by vveliev** [comment]
Yeah i think this is  not an issue with page-object.
