### ISSUE TITLE
Element#parent not working anymore since 2.0.0

### ISSUE THREAD

**Issue by entwanderer** [cheezy/page-object#428]
I recently updated all my gems with bundle update.

Since then the #parent method of Element is not working anymore.
In any case by calling this method i get the error
```
key not found: :getParentElement
```

Is that a mapping problem to the selenium web driver?

Example:
```
span(:total_span, id: 'my_total_span')
...
self.total_span
=> "81,91 €"
self.total_span_element
=> #<Selenium::WebDriver::Element:0xb2c3a2fc id="0.6317482695731407-1">
self.total_span_element.class
=> PageObject::Elements::Span
self.total_span_element.parent
=> key not found: :getParentElement
```

Using:
- Windows 10
- Ruby 2.3.3
- chrome 59
- page-object (2.0.0)
- selenium-webdriver (3.4.3)

Worked fine on:
- page-object (1.2.2)
- selenium-webdriver (3.0.0.beta3.1)

**Comment by entwanderer** [comment]
My quick workaround was
```
self.total_span_element.find_element(:xpath,'..')
=> #<Selenium::WebDriver::Element:0x..f4a325bce id="0.709166454893595-8">
```

**Comment by vveliev** [comment]
did you try using latest version !?

**Comment by titusfortner** [comment]
Looks like page-object has previously relied on Watir Atoms (javascript) for parent.
With Watir 6.2, that atom was deleted in favor of implementing the parent method with xpath to provide a much more flexible pattern that can take additional arguments. (http://watir.com/watir-6-2/)

So either set your gemfile to use watir 6.1 or update to the latest page-object code which implicitly calls the updated watir method directly.

**Comment by AlexisKAndersen** [comment]
looks like this comes down to a version incompatibility issue. Thanks, @titusfortner, for the useful information. I'm closing this. @entwanderer, go ahead and repoen if you're still experiencing this issue after applying one of the changes suggested.
