### ISSUE TITLE
Selenium::Webdriver support broken since 2.1: undefined methods

### ISSUE THREAD

**Issue by imankovskyi** [cheezy/page-object#439]
Hi,
Starting from version 2.1 Selenium Webdriver support seems to be broken. 
I am getting 'NoMethodError: undefined method `goto' for #<Selenium::WebDriver::Chrome' using page-object helper methods: page_url, button , etc.
I am aware that 2.1 is the version where page-object was moved internally to use Watir, but Selenium Webdriver should still be working, right?

My spec file and page-object are attached. 

[example.zip](https://github.com/cheezy/page-object/files/1231739/example.zip)

@browser variable is being instantiated in the same 'Object' scope, with: 

> RSpec.configure do | config |
  config.before(:example) do | test |
     @browser = Selenium::WebDriver::Driver.for :chrome, options: options
   end
end

Error message I'm getting:

> Failure/Error:
       visit YoutubeLanding do |page|
         page.search_video "Test Video"
       end
     NoMethodError:
       undefined method goto' for #<Selenium::WebDriver::Chrome::Driver:0x000000018242a8>
     # /home/user/.rvm/gems/ruby-2.4.1@myset/gems/page-object-2.2/lib/page-object/platforms/watir/page_object.rb:31:in navigate_to'
     # /home/user/.rvm/gems/ruby-2.4.1@myset/gems/page-object-2.2/lib/page-object/accessors.rb:39:in block in page_url'
     # /home/imankovskyi/.rvm/gems/ruby-2.4.1@myset/gems/page-object-2.2/lib/page-object.rb:72:in initialize'
     # /home/imankovskyi/.rvm/gems/ruby-2.4.1@myset/gems/page-object-2.2/lib/page-object/page_factory.rb:74:in new'
     # /home/imankovskyi/.rvm/gems/ruby-2.4.1@myset/gems/page-object-2.2/lib/page-object/page_factory.rb:74:in on_page'
     # /home/imankovskyi/.rvm/gems/ruby-2.4.1@myset/gems/page-object-2.2/lib/page-object/page_factory.rb:53:in visit_page'
     # ./spec/pageobject_spec.rb:25:in block (2 levels) in <top (required)>

Same code works well on page-object version 2.0.

**Comment by charlesgreen** [comment]
I'm having the same issue.

**Comment by titusfortner** [comment]
Page Object has changed its implementation to wrap all `Selenium::WebDriver::Driver` objects inside `Watir::Browser` objects. This allows PO users to take advantage of many of the new Watir features while removing duplicate code and simplifying PO gem. For some reason the driver isn't getting wrapped. I think I found the fix and made a PR with it.

Also worth noting that once this is fixed, it won't be possible to do things like: `@browser.find_elements`. You would either need to change to `@browser.wd.find_elements` or use the Page Object provided means. 

Or, @cheezy we could probably delegate `#find_element`/`#find_elements`/any other Selenium specific method to `#wd` and wrap the result in a `Watir::Element` from which to create a `PageObject::Element`. It would add a lot more complication (and might cause unintended consequences elsewhere), so I'm not sure it is worth the extra backward compatibility...

**Comment by imankovskyi** [comment]
I used page-object from the fixed branch and was able to run the specs with no errors. It seems to work now.
Thank you for help on this.

I saw the PR was just merged into master, does it mean its going to be included into release soon?

**Comment by cheezy** [comment]
I want to get a release out today.
