### ISSUE TITLE
Make a generic "wait_for_ajax" method

### ISSUE THREAD

**Issue by aheward** [cheezy/page-object#46]
Add a generic “wait_for_ajax” method, a la what’s discussed here:

http://agilesoftwaretesting.com/?p=111

and here:

http://tanin.nanakorn.com/watir/wait_for_ajax

Sometimes customized wait statements aren't possible, or become overly-complicated and thus brittle.

**Comment by b1alpha** [comment]
Just tried to use this and couldnt get it to work, didnt see it on your wiki in the ajax section either did I miss it? Would be nice to have an example around of how to call it, is there one I missed? Thanks!
