### ISSUE TITLE
Located element by tagname

### ISSUE THREAD

**Issue by liyucun** [cheezy/page-object#462]
```
<div>
  <bookmark-button custom-attribute-here >
</div>
```

Do we have any methods to locate a non-standard element by its tag-name? For the above case, how can i locate the `bookmark-button` by its attribute in the html?

I came across the [documentation](https://www.rubydoc.info/github/cheezy/page-object/PageObject/ElementLocators), but still failed to figure it out how to get this element.

Thanks a lot

**Comment by stevegibson** [comment]
`button(:my_button, bookmark_button: 'custom-attribute-here')` should do the trick.
See page 122 'Located based on presence of attribute' on the Cucumbers and Cheese book.
Cheers.

**Comment by jkotests** [comment]
You'll need to use the general #element accessor with the `:tag_name` specified:

~~~~~~~~
element(:bookmark, tag_name: 'bookmark-button', custom_attribute_here: 'attribute_value')
~~~~~~~~

**Comment by liyucun** [comment]
Thanks @jkotests @stevegibson
