### ISSUE TITLE
Watir warning for populate_page_with

### ISSUE THREAD

**Issue by marcangel1** [cheezy/page-object#467]
`2018-10-25 12:47:42 WARN Watir ["visible_element"] #visible? behavior will be changing slightly, consider switching to #present? (more details: http://watir.com/element-existentialism/)`

I keep getting this warning when I use `populate_page_with` and fill out text fields. `is_enabled?` for `populate_value` is still using `.visible?`. This is for 2.2.4 with watir 6.1.4 . In the mean time, I just overrode that method because I wanted the warning to go away

**Comment by jkotests** [comment]
@marcangel1 , I'll take a look. 

Note that instead of overriding the method, Watir provides functionality for disabling deprecation warnings (see http://watir.com/watir-6-12/). For this warning, you would do:

~~~~~~~~
Watir.logger.ignore :visible_element
~~~~~~~~

**Comment by jkotests** [comment]
This is fixed in v2.2.6.
