### ISSUE TITLE
Would it be possible to use selenium webdriver selector in Page class ?

### ISSUE THREAD

**Issue by rtcoms** [cheezy/page-object#505]
I'm starting an automation test setup for an enterprise app, Previously I had good experience with watir/PageObject, and so I want to propose this, although just for long term support perspective, I want to convince them that if required we would be able to convert Watir/Page object setup to Selenium/PageObject.

So how should go about converting a simple page like 

```
class LoginPage < Page

  page_url('/sign_in)

  text_field(:username, :id => 'user_login')
  text_field(:password, :id => 'user_password')
  button(:login, :id => 'submit')

  def login_with(user_info)
    populate_page_with(user_info)
    self.login
  end

end
```

to use selenium selectors, instead of `text_field(:username, :id => 'user_login')` ?

**Comment by titusfortner** [comment]
If you are using Ruby Selenium, you should either be using it with Capybara or with Watir. If you do not, you'll need to build out a bunch of your own test logic, and it is not going to be as good as what either of these projects have put together over the years. The Capybara and Watir devs are all Selenium devs as well, so it isn't like one is going to be maintained longer than another, etc.
