### ISSUE TITLE
How to add PageFactory to RSpec?

### ISSUE THREAD

**Issue by fohara** [cheezy/page-object#67]
The documentation only provides information for configuring Cucumber to use PageFactory.  What is the best way to configure RSpec to use PageFactory?

**Comment by naveenb29** [comment]
What's a good place to add  PageObject::PageFactory for runit tests ?

**Comment by cheezy** [comment]
You can add it to your RSpec configuration.  In your spec_helper you can add:

RSpec.configure do |config|
  config.include PageObject::PageFactory
end
